import type { Difficulty } from '../../../platform/types';

/*
 * Lights Out — seeded board generation + exact-par solving.
 *
 * A board is a size×size grid of lights; pressing a cell toggles it and its
 * orthogonal neighbours (a plus shape; on `wrap` boards the neighbours wrap
 * around the edges, torus-style). Boards are generated by applying K random
 * distinct presses to the all-off board, so every board is solvable by
 * construction. `par` is the true MINIMUM number of presses needed, computed
 * with Gaussian elimination over GF(2): press order never matters and
 * pressing a cell twice cancels, so solving is linear algebra mod 2. When
 * the press matrix has a null space (the 4×4 and 5×5 flat boards) the
 * minimum-weight solution is found by enumerating all null-space
 * combinations — the dimensions used here keep that cheap.
 */

export interface LightsOutBoard {
  size: number;
  wrap: boolean;
  seed: number;
  /** initial lights, row-major, 1 = on */
  lights: number[];
  /** true minimum number of presses to clear the board */
  par: number;
  /** one minimum-weight solution (cell indices to press) */
  solution: number[];
}

export interface LightsOutOptions {
  seed?: number;
  size: number;
  wrap: boolean;
  /** number of random distinct scramble presses */
  presses: number;
}

export interface LoTierConfig {
  size: number;
  wrap: boolean;
  parMin: number;
  parMax: number;
}

/** Difficulty tiers — extreme plays on a torus (edges wrap around). */
export const LO_CONFIG: Record<Difficulty, LoTierConfig> = {
  easy: { size: 4, wrap: false, parMin: 4, parMax: 6 },
  medium: { size: 5, wrap: false, parMin: 7, parMax: 9 },
  hard: { size: 6, wrap: false, parMin: 10, parMax: 12 },
  pro: { size: 7, wrap: false, parMin: 12, parMax: 15 },
  extreme: { size: 8, wrap: true, parMin: 14, parMax: 18 }
};

export function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Cells toggled by pressing `i`: itself + orthogonal neighbours (wrapping on torus boards). */
export function pressCells(i: number, size: number, wrap: boolean): number[] {
  const r = Math.floor(i / size);
  const c = i % size;
  const out = [i];
  if (wrap) {
    out.push(((r + size - 1) % size) * size + c);
    out.push(((r + 1) % size) * size + c);
    out.push(r * size + ((c + size - 1) % size));
    out.push(r * size + ((c + 1) % size));
  } else {
    if (r > 0) out.push((r - 1) * size + c);
    if (r < size - 1) out.push((r + 1) * size + c);
    if (c > 0) out.push(r * size + (c - 1));
    if (c < size - 1) out.push(r * size + (c + 1));
  }
  return out;
}

/** Apply a press to a lights array in place. */
export function applyPress(lights: number[], i: number, size: number, wrap: boolean): void {
  for (const c of pressCells(i, size, wrap)) lights[c] ^= 1;
}

/* ---------------- GF(2) linear algebra (bitset rows) ---------------- */

function popcount32(x: number): number {
  x -= (x >> 1) & 0x55555555;
  x = (x & 0x33333333) + ((x >> 2) & 0x33333333);
  x = (x + (x >> 4)) & 0x0f0f0f0f;
  return Math.imul(x, 0x01010101) >> 24;
}

function weight(v: Uint32Array): number {
  let w = 0;
  for (let k = 0; k < v.length; k++) w += popcount32(v[k]);
  return w;
}

function getBit(v: Uint32Array, i: number): number {
  return (v[i >> 5] >>> (i & 31)) & 1;
}

function setBit(v: Uint32Array, i: number): void {
  v[i >> 5] |= 1 << (i & 31);
}

function xorInto(dst: Uint32Array, src: Uint32Array): void {
  for (let k = 0; k < dst.length; k++) dst[k] ^= src[k];
}

/**
 * Minimum-weight solution of `press-matrix · x = lights` over GF(2), i.e.
 * the fewest presses that turn every light off from this state. Returns the
 * cell indices to press, or null when the state is unsolvable (never the
 * case for states reached by pressing, which is how all boards are made).
 */
export function minimalSolution(lights: number[], size: number, wrap: boolean): number[] | null {
  const n = size * size;
  const words = Math.ceil(n / 32);

  // rows[i] = the set of presses that toggle cell i (symmetric: the plus at i)
  const rows: Uint32Array[] = [];
  const aug = new Uint8Array(n);
  for (let i = 0; i < n; i++) {
    const row = new Uint32Array(words);
    for (const j of pressCells(i, size, wrap)) setBit(row, j);
    rows.push(row);
    aug[i] = lights[i] & 1;
  }

  // Gauss–Jordan to reduced row echelon form
  const pivotCol: number[] = [];
  let rank = 0;
  for (let col = 0; col < n && rank < n; col++) {
    let sel = -1;
    for (let r = rank; r < n; r++) {
      if (getBit(rows[r], col)) {
        sel = r;
        break;
      }
    }
    if (sel < 0) continue; // free column
    [rows[rank], rows[sel]] = [rows[sel], rows[rank]];
    const t = aug[rank];
    aug[rank] = aug[sel];
    aug[sel] = t;
    for (let r = 0; r < n; r++) {
      if (r !== rank && getBit(rows[r], col)) {
        xorInto(rows[r], rows[rank]);
        aug[r] ^= aug[rank];
      }
    }
    pivotCol[rank] = col;
    rank++;
  }

  // consistency: a zero row with augmented 1 means unsolvable
  for (let r = rank; r < n; r++) {
    if (aug[r]) {
      let zero = true;
      for (let k = 0; k < words; k++) {
        if (rows[r][k] !== 0) {
          zero = false;
          break;
        }
      }
      if (zero) return null;
    }
  }

  // particular solution: free vars 0, pivot vars from the augmented column
  const x0 = new Uint32Array(words);
  for (let r = 0; r < rank; r++) if (aug[r]) setBit(x0, pivotCol[r]);

  // null-space basis: one vector per free column
  const pivotSet = new Set(pivotCol);
  const basis: Uint32Array[] = [];
  for (let col = 0; col < n; col++) {
    if (pivotSet.has(col)) continue;
    const v = new Uint32Array(words);
    setBit(v, col);
    for (let r = 0; r < rank; r++) if (getBit(rows[r], col)) setBit(v, pivotCol[r]);
    basis.push(v);
  }

  // minimum weight over all 2^d combinations (Gray-code walk). The board
  // sizes used here keep d small (4×4 → 4, 5×5 → 2; 6×6, 7×7 and the 8×8
  // torus are invertible, d = 0).
  let best = x0.slice();
  let bestW = weight(best);
  const d = basis.length;
  if (d > 0 && d <= 20) {
    const cur = x0.slice();
    const total = 1 << d;
    for (let g = 1; g < total; g++) {
      // bit that flips between Gray codes of g-1 and g
      let bit = 0;
      let v = g & -g;
      while (v > 1) {
        v >>>= 1;
        bit++;
      }
      xorInto(cur, basis[bit]);
      const w = weight(cur);
      if (w < bestW) {
        bestW = w;
        best = cur.slice();
      }
    }
  }

  const out: number[] = [];
  for (let i = 0; i < n; i++) if (getBit(best, i)) out.push(i);
  return out;
}

/* ---------------- generation ---------------- */

/**
 * Scramble the all-off board with `presses` random distinct presses (always
 * solvable by construction), then compute the exact par with the GF(2)
 * solver. Deterministic for a given seed.
 */
export function generateLightsOut(opts: LightsOutOptions): LightsOutBoard {
  const seed = (opts.seed ?? Math.floor(Math.random() * 0x7fffffff)) >>> 0;
  const { size, wrap, presses } = opts;
  const n = size * size;
  const rnd = mulberry32(seed || 1);

  // partial Fisher–Yates: pick `presses` distinct cells
  const pool = Array.from({ length: n }, (_, i) => i);
  for (let i = 0; i < presses && i < n; i++) {
    const j = i + Math.floor(rnd() * (n - i));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  const lights = new Array<number>(n).fill(0);
  for (let i = 0; i < presses && i < n; i++) applyPress(lights, pool[i], size, wrap);

  const solution = minimalSolution(lights, size, wrap) ?? [];
  return { size, wrap, seed, lights, par: solution.length, solution };
}

/**
 * Generate a board for a difficulty tier whose par lands inside the tier's
 * band, retrying with derived seeds until it does. Deterministic per seed.
 */
export function generateBoard(difficulty: Difficulty, seed?: number): LightsOutBoard {
  const cfg = LO_CONFIG[difficulty];
  let s = (seed ?? Math.floor(Math.random() * 0x7fffffff)) >>> 0;
  const rnd = mulberry32(s || 1);
  let board: LightsOutBoard | null = null;
  for (let attempt = 0; attempt < 300; attempt++) {
    const presses = cfg.parMin + Math.floor(rnd() * (cfg.parMax - cfg.parMin + 1));
    board = generateLightsOut({ seed: s, size: cfg.size, wrap: cfg.wrap, presses });
    if (board.par >= cfg.parMin && board.par <= cfg.parMax) return board;
    s = (s + 0x9e3779b9) >>> 0;
  }
  // practically unreachable — every attempt is checked above
  return board!;
}
