/*
 * Word Ladder — original word banks + ladder-graph helpers.
 *
 * Three dictionaries of common, fair English words (uppercase A–Z only):
 * 3-letter (easy), 4-letter (medium/hard) and 5-letter (pro/extreme).
 * All lists are hand-authored for this game — generously sized and chosen
 * so the one-letter-change graph is richly connected (word families like
 * -ATCH, -OUND, -IGHT and common plurals interlink the 5-letter tier).
 *
 * Pure TS, no React — validated headlessly by `npm run validate`.
 */

export type LadderLength = 3 | 4 | 5;

const W3 = `
ACE ACT ADD ADO AGE AGO AID AIL AIM AIR ALE ALL AND ANT ANY APE APT ARC ARE ARK ARM ART ASH ASK ATE AWE AXE
BAD BAG BAN BAR BAT BAY BED BEE BEG BET BIB BID BIG BIN BIT BOA BOB BOG BOO BOP BOW BOX BOY BUD BUG BUN BUS BUT BUY BYE
CAB CAM CAN CAP CAR CAT CAW COB COD COG CON COO COP COT COW COY CRY CUB CUE CUP CUT
DAB DAD DAM DAY DEN DEW DID DIG DIM DIN DIP DOE DOG DOT DRY DUB DUD DUE DUG DUO DYE
EAR EAT EBB EGG EGO ELF ELK ELM EMU END EON ERA EVE EYE
FAD FAN FAR FAT FAX FED FEE FEW FIB FIG FIN FIR FIT FIX FLU FLY FOE FOG FOR FOX FRY FUN FUR
GAG GAP GAS GEL GEM GET GIG GIN GNU GOO GOT GUM GUN GUT GUY GYM
HAD HAG HAM HAS HAT HAY HEM HEN HER HEW HEX HEY HID HIM HIP HIS HIT HOE HOG HOP HOT HOW HUB HUE HUG HUM HUT
ICE ICY ILL IMP INK INN ION IRE ITS IVY
JAB JAM JAR JAW JAY JET JIG JOB JOG JOT JOY JUG JUT
KEG KEY KID KIN KIT
LAB LAD LAG LAP LAW LAX LAY LED LEG LET LID LIE LIP LIT LOB LOG LOT LOW LUG
MAD MAN MAP MAR MAT MAX MAY MEN MET MEW MIX MOB MOO MOP MOW MUD MUG MUM
NAB NAG NAP NAY NET NEW NIL NIP NIX NOD NOR NOT NOW NUN NUT
OAK OAR OAT ODD ODE OFF OIL OLD ONE OPT ORB ORE OUR OUT OWE OWL OWN
PAD PAL PAN PAR PAT PAW PAY PEA PEG PEN PEP PET PEW PIE PIG PIN PIP PIT PLY POD POP POT POX PRO PRY PUB PUG PUN PUP PUT
RAG RAM RAN RAP RAT RAW RAY RED RIB RID RIG RIM RIP ROB ROD ROE ROT ROW RUB RUE RUG RUM RUN RUT RYE
SAD SAG SAP SAT SAW SAY SEA SEE SET SEW SHE SHY SIN SIP SIR SIT SIX SKI SKY SLY SOB SOD SON SOP SOW SOY SPA SPY STY SUB SUM SUN SUP
TAB TAD TAG TAN TAP TAR TAX TEA TEN THE THY TIC TIE TIN TIP TOE TON TOO TOP TOT TOW TOY TRY TUB TUG TUX TWO
URN USE
VAN VAT VET VIA VIE VOW
WAD WAG WAN WAR WAS WAX WAY WEB WED WEE WET WHO WHY WIG WIN WIT WOE WOK WON WOO WOW
YAK YAM YAP YAW YEN YES YET YEW YIN YOU YUM
ZAP ZEN ZIG ZIP ZOO
`;

const W4 = `
ABLE ACHE ACID AGED AJAR AKIN ALSO AREA ARMY ATOP AUNT AVID AWAY
BABE BACK BAIT BAKE BALD BALE BALL BAND BANE BANG BANK BARE BARK BARN BASE BASH BASK BASS BATH
BEAD BEAK BEAM BEAN BEAR BEAT BEEF BEEN BEER BEET BELL BELT BEND BENT BEST BIKE BILL BIND BIRD BITE
BLED BLEW BLOB BLOT BLOW BLUE BLUR BOAR BOAT BODE BOIL BOLD BOLT BOMB BOND BONE BOOK BOOM BOOT BORE BORN BOSS BOTH BOUT BOWL
BRAG BRAN BRAT BRED BREW BRIM BUCK BULB BULK BULL BUMP BUNK BURN BUSH BUST BUSY BUZZ
CAFE CAGE CAKE CALF CALL CALM CAME CAMP CANE CAPE CARD CARE CART CASE CASH CAST CAVE CELL CENT
CHAT CHEF CHEW CHIN CHIP CHOP CITE CITY CLAD CLAM CLAN CLAP CLAW CLAY CLIP CLOG CLOT CLUB CLUE
COAL COAT CODE COIL COIN COLD COLT COMB COME CONE COOK COOL COPE COPY CORD CORE CORK CORN COST COVE COZY
CRAB CRAM CREW CRIB CROP CROW CUBE CUFF CULT CURB CURE CURL CUTE
DAME DAMP DARE DARK DART DASH DATA DATE DAWN DEAF DEAL DEAR DEBT DECK DEED DEEP DEER DENT DENY DESK
DIAL DICE DIET DIME DINE DIRE DIRT DISH DIVE DOCK DOES DOLL DOME DONE DOOM DOOR DOSE DOTE DOVE DOWN DOZE
DRAG DRAW DREW DRIP DROP DRUM DUAL DUCK DUDE DUEL DUET DULL DUMB DUMP DUNE DUSK DUST DUTY
EACH EARN EASE EAST EASY ECHO EDGE EDIT ELSE EMIT ENVY EPIC EVEN EVER EXAM EXIT EYED
FACE FACT FADE FAIL FAIR FAKE FALL FAME FANG FARE FARM FAST FATE FAWN FEAR FEAT FEED FEEL FEET FELL FELT FERN FEUD
FILE FILL FILM FIND FINE FIRE FIRM FISH FIST FIVE
FLAG FLAP FLAT FLAW FLEA FLED FLEE FLEW FLIP FLOP FLOW
FOAM FOIL FOLD FOLK FOND FONT FOOD FOOL FOOT FORE FORK FORM FORT FOUL FOUR FOWL FREE FROG FROM FUEL FULL FUME FUND FUSE FUSS
GAIN GAIT GALE GAME GANG GAPE GASP GATE GAVE GAZE GEAR GENE GIFT GILL GIRL GIVE
GLAD GLEE GLOW GLUE GNAT GOAL GOAT GOES GOLD GOLF GONE GONG GOOD GOWN
GRAB GRAM GRAY GREW GREY GRID GRIM GRIN GRIP GROW GRUB GULF GULL GUSH GUST
HACK HAIL HAIR HALE HALF HALL HALT HAND HANG HARD HARE HARM HARP HASH HATE HAUL HAVE HAWK HAZE
HEAD HEAL HEAP HEAR HEAT HEED HEEL HEIR HELD HELM HELP HEMP HERB HERD HERE HERO
HIDE HIGH HIKE HILL HILT HIND HINT HIRE HIVE
HOLD HOLE HOLY HOME HONE HOOD HOOF HOOK HOOP HOPE HORN HOSE HOST HOUR HOWL
HUGE HULL HUMP HUNG HUNT HURL HURT HUSH HYMN
ICON IDEA IDLE INCH INTO IRON ITCH ITEM
JADE JAIL JAZZ JEEP JEST JOIN JOKE JOLT JUMP JUNK JURY JUST
KEEN KEEP KELP KEPT KICK KIND KING KISS KITE KNEE KNEW KNIT KNOB KNOT KNOW
LACE LACK LADY LAID LAIR LAKE LAMB LAME LAMP LAND LANE LARD LASH LAST LATE LAVA LAWN LAZY
LEAD LEAF LEAK LEAN LEAP LEFT LEND LENS LENT LESS LEST LICK LIFE LIFT LIKE LIMB LIME LIMP LINE LINK LINT LION LIST LIVE
LOAD LOAF LOAN LOBE LOCK LOFT LOGO LONE LONG LOOK LOOM LOOP LOOT LORD LORE LOSE LOSS LOST LOUD LOVE
LUCK LUMP LUNG LURE LURK LUSH
MADE MAID MAIL MAIN MAKE MALE MALL MALT MANE MANY MARE MARK MASH MASK MAST MATE MATH MAZE
MEAL MEAN MEAT MEEK MEET MELD MELT MEMO MEND MENU MERE MESH MESS MICE MILD MILE MILK MILL MIME MIND MINE MINT MIST MITE
MOAN MOAT MOCK MODE MOLD MOLE MONK MOOD MOON MOOR MOSS MOST MOTH MOVE MUCH MULE MUST MUTE MYTH
NAIL NAME NAPE NAVY NEAR NEAT NECK NEED NEON NEST NEWS NEXT NICE NINE NODE NONE NOON NORM NOSE NOTE NOUN NUMB
OATH OBEY ODDS ONCE ONLY ONTO OPEN ORAL OVAL OVEN OVER
PACE PACK PACT PAGE PAID PAIL PAIN PAIR PALE PALM PANE PANT PARK PART PASS PAST PATH PAVE PAWN
PEAK PEAR PEAT PECK PEEL PEER PELT PERK PEST PICK PIER PIKE PILE PILL PINE PINK PINT PIPE PITY
PLAN PLAY PLEA PLOT PLOW PLUG PLUM PLUS POEM POET POKE POLE POLL POND PONY POOL POOR PORE PORK PORT POSE POST POUR POUT
PRAY PREY PROP PULL PUMP PURE PUSH
QUIT QUIZ
RACE RACK RAFT RAGE RAID RAIL RAIN RAKE RAMP RANG RANK RANT RARE RASH RATE RAVE
READ REAL REAP REAR REED REEF REEL RENT REST RICE RICH RIDE RIFT RIND RING RINK RIOT RIPE RISE RISK
ROAD ROAM ROAR ROBE ROCK RODE ROLE ROLL ROOF ROOK ROOM ROOT ROPE ROSE ROSY ROTE ROVE RUDE RUIN RULE RUNG RUNT RUSH RUST
SACK SAFE SAGA SAGE SAID SAIL SAKE SALE SALT SAME SAND SANE SANG SANK SASH SAVE SCAN SCAR
SEAL SEAM SEAT SEED SEEK SEEM SEEN SEEP SELF SELL SEND SENT SHED SHIN SHIP SHOE SHOP SHOT SHOW SHUT
SICK SIDE SIGH SIGN SILK SILL SING SINK SITE SIZE SKID SKIN SKIP
SLAB SLAM SLAP SLED SLEW SLID SLIM SLIP SLOT SLOW SLUG SNAP SNOW
SOAK SOAP SOAR SOCK SODA SOFA SOFT SOIL SOLD SOLE SOME SONG SOON SORE SORT SOUL SOUP SOUR
SPAN SPAR SPIN SPOT SPUN SPUR STAB STAR STAY STEM STEP STEW STIR STOP STOW STUB STUN
SUCH SUIT SUNG SUNK SURE SWAB SWAM SWAN SWAP SWAY SWIM
TACK TACO TAIL TAKE TALE TALK TALL TAME TANK TAPE TART TASK TAUT TAXI TEAK TEAL TEAM TEAR TEEN TELL TEND TENT TERM TEST TEXT
THAN THAT THAW THEM THEN THEY THIN THIS THUD TICK TIDE TIDY TIER TILE TILL TILT TIME TINT TINY TIRE
TOAD TOIL TOLD TOLL TOMB TONE TOOK TOOL TORE TORN TOSS TOUR TOWN
TRAP TRAY TREE TREK TRIM TRIO TRIP TROT TRUE TUBA TUBE TUCK TUNA TUNE TURF TURN TUSK TWIG TWIN TYPE
UGLY UNDO UNIT UPON URGE USED USER
VAIN VANE VASE VAST VEAL VEIL VEIN VENT VERB VERY VEST VIBE VIEW VINE VISA VOID VOLT VOTE
WADE WAGE WAIL WAIT WAKE WALK WALL WAND WANE WANT WARD WARE WARM WARN WART WASH WASP WAVE WAVY
WEAK WEAR WEED WEEK WEEP WELD WELL WENT WEPT WEST WHAT WHEN WHIM WHIP WHOM WICK WIDE WIFE WILD WILL WILT
WIND WINE WING WINK WIPE WIRE WISE WISH WITH WOKE WOLF WOOD WOOL WORD WORE WORK WORM WORN WOVE WRAP WREN
YARD YARN YAWN YEAR YELL YOGA YOUR ZERO ZEST ZINC ZONE ZOOM
`;

const W5 = `
ABOUT ABOVE ACTOR ADAPT ADMIT ADOPT AFTER AGAIN AGENT AGREE AHEAD ALARM ALBUM ALERT ALIKE ALIVE ALLOW ALONE ALONG ALOUD ALTER
ANGEL ANGER ANGLE ANGRY ANKLE APART APPLE APPLY ARENA ARGUE ARISE ARMOR AROMA ARRAY ARROW ASIDE ASSET ATLAS AUDIO AVOID AWAKE AWARD AWARE
BADGE BAKER BASIC BASIN BATCH BATHE BEACH BEADS BEANS BEARD BEARS BEAST BEATS BEGAN BEGIN BEGUN BEING BELLY BELOW BELTS BENCH BENDS BERRY
BILLS BIRTH BISON BLACK BLADE BLAME BLAND BLANK BLAST BLAZE BLEED BLEND BLESS BLIND BLINK BLISS BLOCK BLOND BLOOD BLOOM BLOWN BLUFF BLUNT BLUSH
BOARD BOAST BOATS BONES BONUS BOOKS BOOST BOOTH BOOTS BOUND BOXER BRAID BRAIN BRAKE BRAND BRASS BRAVE BREAD BREAK BREED
BRICK BRIDE BRIEF BRINE BRING BRINK BRISK BROAD BROKE BROOK BROOM BROTH BROWN BRUSH BUDDY BUILD BUILT BULKY BUNCH BUNNY BURNT BURST BUYER
CABIN CABLE CANAL CANDY CANOE CARDS CARES CARGO CARRY CARTS CARVE CATCH CAUSE CEASE CEDAR CELLO
CHAIN CHAIR CHALK CHAMP CHANT CHAOS CHARM CHART CHASE CHEAP CHEAT CHECK CHEEK CHEER CHESS CHEST CHICK CHIEF CHILD CHILI CHILL CHIME CHIRP
CHOIR CHORD CHORE CHOSE CHUNK CIDER CIVIC CIVIL CLAIM CLAMP CLASH CLASS CLEAN CLEAR CLERK CLICK CLIFF CLIMB CLING CLOAK CLOCK CLONE CLOSE CLOTH CLOUD CLOWN
COACH COAST COATS COBRA COCOA COINS COLOR COMET COMIC CORAL CORDS COUCH COUGH COULD COUNT COURT COVER
CRACK CRAFT CRANE CRASH CRATE CRAWL CRAZE CRAZY CREAM CREEK CREEP CREPT CREST CRIME CRISP CROSS CROWD CROWN CRUDE CRUEL CRUMB CRUSH CRUST CURVE CYCLE
DAILY DAIRY DAISY DANCE DARES DATES DEALT DEATH DEBUT DECAY DELAY DELTA DENIM DENSE DEPTH DERBY DEVIL DIARY DIGIT DINER DINES DIRTY DITCH DIVER DOING DONOR DOUBT DOUGH DOZEN
DRAFT DRAIN DRAMA DRANK DRAPE DRAWN DREAD DREAM DRESS DRIED DRIFT DRILL DRINK DRIVE DROVE DROWN DRUNK DRYER DUSTY DWELL
EAGER EAGLE EARLY EARTH EATEN EIGHT ELBOW ELDER ELITE EMPTY ENEMY ENJOY ENTER ENTRY EQUAL ERROR ESSAY EVENT EVERY EXACT EXIST EXTRA
FABLE FAINT FAIRY FAITH FALSE FANCY FARES FATAL FAULT FAVOR FEARS FEAST FEATS FENCE FERRY FETCH FEVER FIBER FIELD FIERY FIFTH FIFTY FIGHT FILLS FINAL FINCH FIRST
FLAIR FLAKE FLAME FLASH FLASK FLEET FLESH FLICK FLING FLINT FLOAT FLOCK FLOOD FLOOR FLOUR FLOWN FLUID FLUSH FLUTE
FOCUS FOGGY FORCE FORGE FORTH FORTY FORUM FOUND FRAUD FRESH FRIED FRONT FROST FROWN FROZE FRUIT FUDGE FULLY FUNNY
GATES GAUGE GEARS GECKO GHOST GIANT GIVEN GIVER GLARE GLASS GLAZE GLIDE GLOBE GLOOM GLORY GLOVE GOATS GOING GOOSE
GRACE GRADE GRAIN GRAND GRANT GRAPE GRAPH GRASP GRASS GRAVE GRAVY GREAT GREED GREEN GREET GRIEF GRILL GRIME GRIND GROAN GROOM GROVE GROWL GROWN GUARD GUESS GUEST GUIDE GUILT
HABIT HANDS HANDY HAPPY HARSH HASTE HATCH HAUNT HAVEN HAVOC HEARD HEARS HEART HEATS HEAVY HEDGE HELLO HENCE HILLS HINGE HITCH HOARD HOBBY HOIST
HONEY HONOR HOOKS HORSE HOTEL HOUND HOUSE HOVER HUMAN HUMID HUMOR HUNCH HURRY
IDEAL IMAGE IMPLY INDEX INNER INPUT IRONY ISSUE IVORY
JEANS JELLY JEWEL JOINT JOLLY JUDGE JUICE JUICY
KAYAK KILLS KNACK KNEEL KNIFE KNOCK KNOWN
LABEL LABOR LANDS LARGE LASER LATCH LATER LAUGH LAYER LEARN LEASE LEASH LEAST LEAVE LEDGE LEGAL LEMON LEVEL LEVER
LIGHT LILAC LIMIT LINEN LINES LIVER LLAMA LOBBY LOCAL LODGE LOGIC LOOKS LOOSE LOSER LOVER LOWER LOYAL LUCKY LUNAR LUNCH LUNGE LYING
MAGIC MAJOR MAKER MANGO MAPLE MARCH MARES MARSH MATCH MATES MAYBE MAYOR MEANT MEATS MEDAL MEDIA MELON MERCY MERGE MERIT MERRY METAL METER MICRO MIDST MIGHT
MILLS MIMIC MINER MINES MINOR MINUS MIXER MODEL MODEM MOIST MONEY MONTH MOOSE MORAL MOTEL MOTOR MOUND MOUNT MOUSE MOUTH MOVER MOVIE MOWER MUDDY MUSIC
NASTY NAVAL NERVE NEVER NEWER NEWLY NIGHT NINES NINTH NOBLE NOISE NOISY NORTH NOTCH NOTES NOVEL NURSE NYLON
OASIS OCCUR OCEAN OFFER OFTEN OLIVE ONION ONSET OPERA ORBIT ORDER ORGAN OTHER OTTER OUGHT OUNCE OUTER OWNER OZONE
PACKS PAINT PANDA PANEL PANIC PANTS PAPER PARTY PASTA PASTE PATCH PATIO PAUSE PEACE PEACH PEARL PEARS PEDAL PENNY PETAL PHASE PHONE PHOTO PIANO PIECE
PILLS PILOT PINCH PINES PITCH PIVOT PIXEL PIZZA PLACE PLAIN PLANE PLANK PLANT PLATE PLAZA PLEAD PLUCK PLUMP PLUSH POINT POLAR PORCH POUCH POUND POWER
PRESS PRICE PRIDE PRIME PRINT PRIZE PROBE PRONE PROOF PROUD PROVE PRUNE PULSE PUNCH PUPIL PUPPY PURSE
QUACK QUAIL QUAKE QUART QUEEN QUERY QUEST QUEUE QUICK QUIET QUILT QUIRK QUITE QUOTA QUOTE
RADAR RADIO RAINY RAISE RALLY RANCH RANGE RAPID RATES RATIO RAVEN RAZOR REACH REACT READY REALM REBEL REFER REIGN RELAX RELAY REPAY REPLY RESET RETRY RHYME
RIDER RIDGE RIFLE RIGHT RIGID RINSE RIPEN RISEN RISKY RIVAL RIVER ROAST ROBIN ROBOT ROCKY ROGUE ROTOR ROUGH ROUND ROUTE ROYAL RUGBY RULER RUMOR RURAL RUSTY
SACKS SADLY SAINT SALAD SALON SALSA SALTY SANDS SANDY SAUCE SAUNA SCALE SCALP SCARE SCARF SCENE SCENT SCOOP SCOPE SCORE SCOUT SCRAP SCRUB SEATS SEDAN SEIZE SENSE SERVE SETUP SEVEN
SHACK SHADE SHADY SHAFT SHAKE SHAKY SHALE SHALL SHAME SHAPE SHARE SHARK SHARP SHAVE SHAWL SHEEP SHEER SHEET SHELF SHELL SHIFT SHINE SHINY SHIRT SHOCK SHONE SHOOK SHOOT SHORE SHORT SHOUT SHOVE SHOWN SHRUB SHRUG
SIEGE SIGHT SILKY SILLY SINCE SIREN SIXTH SIXTY SKATE SKILL SKIRT SKULL SLANG SLANT SLASH SLATE SLEEK SLEEP SLEET SLICE SLIDE SLIME SLING SLOPE SLOTH
SMALL SMART SMASH SMELL SMILE SMOKE SNACK SNAIL SNAKE SNEAK SNORE SNOUT SNOWY SOBER SOLAR SOLID SOLVE SORRY SOUND SOUTH
SPACE SPADE SPARE SPARK SPEAK SPEAR SPEED SPELL SPEND SPENT SPICE SPICY SPIKE SPILL SPINE SPLIT SPOIL SPOKE SPOON SPORT SPRAY
STACK STAFF STAGE STAIN STAIR STAKE STALE STALL STAMP STAND STARE STARK START STATE STEAK STEAL STEAM STEEL STEEP STEER STICK STIFF STILL STING STOCK STOLE STONE STOOD STOOL STORE STORK STORM STORY STOUT STOVE STRAP STRAW STRAY STRIP STUCK STUDY STUFF STUMP STUNT STYLE
SUGAR SUITE SUNNY SUPER SURGE SWAMP SWEAR SWEAT SWEEP SWEET SWELL SWEPT SWIFT SWING SWIRL SWORD SWORE
TABLE TACKS TAKEN TALLY TANGO TASTE TASTY TEACH TEARS TEASE TEETH TEMPO TENSE TENTH THANK THEFT THEIR THEME THERE THESE THICK THIEF THIGH THING THINK THIRD THORN THOSE THREE THREW THROW THUMB THUMP
TIDAL TIGER TIGHT TIMER TIMID TITLE TOAST TODAY TOKEN TONIC TOOTH TOPIC TORCH TOTAL TOUCH TOUGH TOWEL TOWER TOXIC
TRACE TRACK TRADE TRAIL TRAIN TRAIT TRASH TREAD TREAT TREND TRIAL TRIBE TRICK TRIED TROOP TROUT TRUCK TRULY TRUNK TRUST TRUTH TULIP TURBO TUTOR TWICE TWIST
UNCLE UNDER UNION UNITE UNITY UNTIL UPPER UPSET URBAN USAGE USHER USUAL
VAGUE VALID VALUE VALVE VAPOR VAULT VENOM VENUE VERSE VIDEO VIGOR VILLA VINES VINYL VIRUS VISIT VITAL VIVID VOCAL VOICE VOTER VOWEL
WAGON WAIST WALTZ WARDS WARES WASTE WATCH WATER WEARS WEARY WEAVE WEDGE WEIGH WEIRD WHALE WHARF WHEAT WHEEL WHERE WHICH WHILE WHIRL WHISK WHITE WHOLE WHOSE
WIDEN WIDER WIDOW WIDTH WILLS WINCH WINDY WINES WISER WITCH WITTY WOMAN WOMEN WORDS WORLD WORRY WORSE WORST WORTH WOUND WOVEN WRECK WRIST WRITE WRONG WROTE
YACHT YEARN YEARS YEAST YIELD YOUNG YOURS YOUTH ZEBRA
`;

function parse(raw: string): string[] {
  return raw.trim().split(/\s+/);
}

export const WORDS3: readonly string[] = parse(W3);
export const WORDS4: readonly string[] = parse(W4);
export const WORDS5: readonly string[] = parse(W5);

export const DICTS: Record<LadderLength, readonly string[]> = {
  3: WORDS3,
  4: WORDS4,
  5: WORDS5
};

const setCache = new Map<LadderLength, ReadonlySet<string>>();

/** Fast membership lookup for one tier's dictionary. */
export function wordSet(length: LadderLength): ReadonlySet<string> {
  let s = setCache.get(length);
  if (!s) {
    s = new Set(DICTS[length]);
    setCache.set(length, s);
  }
  return s;
}

/* ---------- one-letter-change graph ---------- */

const graphCache = new WeakMap<object, Map<string, string[]>>();

/**
 * Adjacency of the ladder graph (words differing in exactly one letter),
 * built via wildcard buckets (C_T etc.) and cached per dictionary array.
 */
export function buildGraph(dict: readonly string[]): Map<string, string[]> {
  const cached = graphCache.get(dict as object);
  if (cached) return cached;
  const buckets = new Map<string, string[]>();
  for (const w of dict) {
    for (let i = 0; i < w.length; i++) {
      const pat = w.slice(0, i) + '*' + w.slice(i + 1);
      const arr = buckets.get(pat);
      if (arr) arr.push(w);
      else buckets.set(pat, [w]);
    }
  }
  const graph = new Map<string, string[]>();
  for (const w of dict) graph.set(w, []);
  for (const arr of buckets.values()) {
    if (arr.length < 2) continue;
    for (let i = 0; i < arr.length; i++) {
      for (let j = 0; j < arr.length; j++) {
        if (i !== j) graph.get(arr[i])!.push(arr[j]);
      }
    }
  }
  graphCache.set(dict as object, graph);
  return graph;
}

/** All dictionary words one letter away from `word`. */
export function neighbors(word: string, dict: readonly string[]): string[] {
  const fromGraph = buildGraph(dict).get(word);
  if (fromGraph) return fromGraph;
  // word not in dict (e.g. probing a draft): scan directly
  const out: string[] = [];
  for (const w of dict) {
    if (w.length !== word.length) continue;
    let diff = 0;
    for (let i = 0; i < w.length && diff < 2; i++) if (w[i] !== word[i]) diff++;
    if (diff === 1) out.push(w);
  }
  return out;
}

/** BFS distances (in rungs) from `from` to every reachable dictionary word. */
export function distanceMap(from: string, dict: readonly string[]): Map<string, number> {
  const graph = buildGraph(dict);
  const dist = new Map<string, number>();
  dist.set(from, 0);
  let frontier = [from];
  let d = 0;
  while (frontier.length) {
    d++;
    const next: string[] = [];
    for (const w of frontier) {
      for (const n of graph.get(w) ?? []) {
        if (!dist.has(n)) {
          dist.set(n, d);
          next.push(n);
        }
      }
    }
    frontier = next;
  }
  return dist;
}

/** Shortest ladder [a, …, b] (BFS), or null when no ladder exists. */
export function shortestPath(a: string, b: string, dict: readonly string[]): string[] | null {
  if (a === b) return [a];
  const graph = buildGraph(dict);
  const parent = new Map<string, string>();
  parent.set(a, a);
  let frontier = [a];
  while (frontier.length) {
    const next: string[] = [];
    for (const w of frontier) {
      for (const n of graph.get(w) ?? []) {
        if (parent.has(n)) continue;
        parent.set(n, w);
        if (n === b) {
          const path = [b];
          let cur = b;
          while (cur !== a) {
            cur = parent.get(cur)!;
            path.push(cur);
          }
          return path.reverse();
        }
        next.push(n);
      }
    }
    frontier = next;
  }
  return null;
}

/* ---------- bank validation (run by npm run validate) ---------- */

const MIN_SIZES: Record<LadderLength, number> = { 3: 300, 4: 500, 5: 450 };

/** Integrity check for the hand-authored banks: sizes, uniqueness, charset. */
export function validateLadderBank(): { ok: boolean; issues: string[] } {
  const issues: string[] = [];
  for (const len of [3, 4, 5] as LadderLength[]) {
    const list = DICTS[len];
    if (list.length < MIN_SIZES[len]) {
      issues.push(`${len}-letter bank too small: ${list.length} < ${MIN_SIZES[len]}`);
    }
    const seen = new Set<string>();
    for (const w of list) {
      if (w.length !== len) issues.push(`${len}-letter bank: "${w}" has wrong length`);
      if (!/^[A-Z]+$/.test(w)) issues.push(`${len}-letter bank: "${w}" has invalid characters`);
      if (seen.has(w)) issues.push(`${len}-letter bank: duplicate "${w}"`);
      seen.add(w);
    }
  }
  return { ok: issues.length === 0, issues };
}
