/*
 * Word Guess — hand-authored original word banks.
 *
 * Two kinds of list per word length:
 *  - ANSWERS: common, fair words a secret can be drawn from (hard tier uses
 *    a separate bank of rarer-but-real 5-letter words).
 *  - EXTRA: additional legitimate words (plurals, verb forms, adjectives…)
 *    accepted as guesses but never used as secrets. ALLOWED = ANSWERS ∪ EXTRA.
 *
 * All words are uppercase A–Z, no proper nouns. Answer banks avoid plurals
 * and inflected forms; the EXTRA banks are deliberately generous so real
 * words don't get rejected. `validateWordGuessBank()` (run by
 * `npm run validate`) enforces lengths, charset, duplicates, bank sizes,
 * answers ⊆ allowed, answer/extra overlap and rare↔common disjointness.
 */

function bank(raw: string): string[] {
  return raw.trim().split(/\s+/);
}

/* ---------------------------------------------------------------- 4 letters */

export const ANSWERS_4 = bank(`
ABLE ACID AREA ARMY ATOM AUNT AUTO BABY BACK BALL
BAND BANK BASE BATH BEAM BEAN BEAR BEAT BELL BELT
BEST BIRD BLUE BOAT BODY BONE BOOK BOOT BOSS BOWL
BURN BUSY CAGE CAKE CALL CALM CAMP CARD CARE CASE
CASH CAST CAVE CELL CHAT CHEF CITY CLUB COAL COAT
CODE COIN COLD COOK COOL COPY CORN COST CREW CROP
DARK DATE DAWN DEAL DEBT DECK DEEP DEER DESK DIET
DISH DOOR DOWN DRAW DROP DRUM DUCK DUST DUTY EACH
EAST EASY EDGE EXIT FACE FACT FAIR FALL FARM FAST
FEAR FEED FEEL FILE FILM FIND FINE FIRE FIRM FISH
FIVE FLAG FLAT FLOW FOLD FOOD FOOT FORK FORM FORT
FREE FROG FUEL FULL GAME GATE GIFT GIRL GLAD GOAL
GOAT GOLD GOOD GROW HAIR HALF HALL HAND HARD HARM
HEAD HEAR HEAT HERO HIGH HILL HOLD HOLE HOME HOPE
HORN HOUR HUGE HUNT IDEA IRON ITEM JOIN JUMP JUST
KEEP KIND KING KNEE KNOW LAKE LAMP LAND LAST LATE
LEAF LEAN LIFE LIFT LINE LION LIST LOAD LOCK LONG
LOOK LOUD LOVE LUCK MAIL MAIN MAKE MANY MARK MASK
MEAL MEAT MILD MILE MILK MIND MINE MOON MOVE MUCH
NAME NEAR NECK NEST NEWS NEXT NICE NINE NOTE OPEN
OVEN OVER PACK PAGE PAIN PAIR PALM PARK PART PASS
PAST PATH PEAK PICK PLAN PLAY POEM POND POOL PORT
POST PULL PUSH RACE RAIN RARE READ REAL REST RICE
RICH RIDE RING RISE RISK ROAD ROCK ROLE ROLL ROOF
ROOM ROOT ROPE ROSE RULE SAFE SAIL SALT SAME SAND
SEAT SEED SELF SELL SEND SHIP SHOE SHOP SHOW SICK
SIDE SIGN SING SITE SIZE SKIN SLOW SNOW SOAP SOFT
SOIL SONG SOON SORT SOUP SPOT STAR STAY STEP STOP
SUIT SURE SWIM TAIL TAKE TALK TALL TASK TEAM TELL
TENT TEST TEXT THIN TIDE TIME TINY TOOL TOWN TREE
TRIP TRUE TURN TWIN UNIT VAST VERY VIEW VOTE WAIT
WALK WALL WARM WASH WAVE WEAR WEEK WELL WEST WIDE
WIFE WILD WIND WINE WING WISE WISH WOOD WOOL WORD
WORK YARD YEAR ZERO ZONE
`);

export const EXTRA_4 = bank(`
ACES ACHE ACRE AGED AIDE AIMS AIRS AJAR ALSO ALTO
ANTS APES ARCH ARCS ARMS ARTS AXES AXLE BAGS BAIT
BAKE BALD BALE BANG BARE BARK BARN BARS BASS BATS
BAYS BEAD BEAK BEDS BEEF BEEN BEES BEGS BEND BENT
BETS BIAS BIDS BIKE BILL BINS BITE BITS BLED BLEW
BLOB BLOT BLUR BOAR BOGS BOIL BOLD BOLT BOMB BOND
BOOM BORE BORN BOTH BOWS BRAG BRAN BRAT BRED BREW
BRIM BROW BUDS BUGS BULB BULK BULL BUMP BUNS BUOY
BUST BUYS CABS CAFE CALF CAME CANE CANS CAPE CAPS
CARS CART CATS CHEW CHIC CHIN CHIP CHOP CITE CLAD
CLAM CLAN CLAP CLAW CLAY CLIP CLOG CLOT CLUE COBS
COIL COLA COLT COMB COME CONE COPE COPS CORD CORE
CORK COTS COVE COWS COZY CRAB CRAM CUBE CUBS CUES
CUFF CULT CUPS CURB CURD CURE CURL CUTE CUTS DAMP
DAMS DARE DART DASH DAYS DAZE DEAD DEAF DENS DENT
DENY DICE DIED DIES DIME DINE DIPS DIRE DIRT DISC
DIVE DOCK DOES DOGS DOLL DOME DONE DORM DOSE DOTS
DOVE DOZE DRAB DRAG DREW DRIP DUDE DUEL DUES DUET
DULL DUMB DUMP DUNE DUSK DYED DYES EARN EARS EASE
EATS ECHO EDGY EELS EGGS EGOS ELMS ELSE ENDS ENVY
EPIC ERAS EVEN EVER EYED EYES FADE FADS FAKE FAME
FANG FANS FARE FATE FAWN FAZE FEAT FEES FEET FELL
FELT FERN FEUD FIGS FILL FINS FIST FITS FLAP FLAW
FLEA FLED FLEE FLEW FLEX FLIP FOAL FOAM FOES FOGS
FOIL FOND FONT FOUL FOUR FOWL FOXY FRAY FRET FROM
FUME FUND FURY FUSE FUSS GAIN GAIT GALA GALE GANG
GAPE GAPS GASP GAVE GAZE GEAR GELS GEMS GENE GETS
GIGS GILL GIST GIVE GLEE GLOW GLUE GNAT GOES GONE
GOWN GRAB GRAM GRAY GREW GRID GRIM GRIN GRIP GRIT
GULF GULL GULP GUMS GUSH GUST GUTS GUYS HACK HAIL
HALO HALT HAMS HARE HARP HATS HAUL HAWK HAZE HEAL
HEAP HEED HEEL HEIR HELD HELM HELP HEMS HENS HERB
HERD HERE HERS HIDE HIKE HINT HIPS HIRE HISS HITS
HIVE HOAX HOGS HOLY HOOD HOOF HOOK HOOT HOPS HOSE
HOST HOWL HUBS HUES HUGS HULL HUMS HUNG HURL HURT
HUSH HUTS HYMN ICED ICON IDLE IDOL INCH INKS INNS
INTO IONS ISLE ITCH JADE JAIL JAMS JARS JAWS JAZZ
JEEP JETS JIGS JOBS JOGS JOKE JOLT JOTS JOYS JUGS
JURY KEEN KEGS KEPT KEYS KICK KIDS KILN KILT KISS
KITE KITS KNEW KNIT KNOB KNOT LABS LACE LACK LADS
LADY LAGS LAID LAIR LAMB LANE LAPS LARK LASH LAVA
LAWN LAWS LAZY LEAD LEAP LEFT LEGS LEND LENS LENT
LESS LETS LEVY LIAR LICE LICK LIDS LIES LIKE LIMB
LIME LIMP LINK LINT LIPS LISP LIVE LOAF LOAN LOBE
LOBS LOGO LOGS LONE LOOM LOOP LOOT LORD LOSE LOSS
LOST LOTS LUMP LUNG LURE LURK LUSH LUTE MADE MAID
MALE MALL MANE MAPS MARE MASH MAST MATE MATH MATS
MAUL MAZE MEAN MEEK MEET MELT MEMO MEND MENU MEOW
MERE MESH MESS MICE MILL MIME MINT MIST MITT MOAN
MOAT MOBS MOCK MODE MOLD MOLE MONK MOOD MOPS MOSS
MOST MOTH MUCK MUGS MULE MUSE MUST MUTE MYTH NAGS
NAIL NAPS NAVY NEAT NEED NEON NETS NEWT NODE NODS
NOON NORM NOSE NOSY NOUN NUMB NUNS NUTS OAKS OARS
OATH OATS OBEY ODDS ODES ODOR OILS OILY OMIT ONCE
ONES ONLY ONTO OOZE OPAL ORAL ORBS ORES OUCH OURS
OUST OUTS OVAL OWED OWES OWLS OWNS PACE PACT PADS
PAID PAIL PALE PANE PANG PANS PANT PAWS PAYS PEAR
PEAS PEAT PECK PEEK PEEL PEER PEGS PELT PENS PERK
PEST PETS PIER PIES PIGS PIKE PILE PILL PINE PINK
PINS PINT PIPE PITS PITY PLEA PLOT PLOW PLOY PLUG
PLUM PLUS PODS POET POKE POLE POLL POMP PONY POPS
PORE PORK POSE POTS POUR POUT PRAY PREY PROD PROP
PROS PUBS PUFF PUMP PUNS PUNY PUPS PURE PUTS QUIT
QUIZ RACK RAFT RAGE RAGS RAID RAIL RAKE RAMP RAMS
RANG RANK RANT RAPS RASH RATE RATS RAYS REAP REAR
REDO REED REEF REEL REFS REIN RELY RENT RIBS RIDS
RIFT RIGS RIMS RIND RIPE RIPS ROAM ROAR ROBE ROBS
RODE RODS ROMP ROTS ROWS RUBS RUBY RUDE RUGS RUIN
RUNG RUNS RUNT RUSH RUST RUTS SACK SAGA SAGE SAID
SAKE SALE SANE SANG SANK SAPS SASH SAWS SAYS SCAB
SCAM SCAN SCAR SEAL SEAM SEAS SECT SEEK SEEM SEEN
SEEP SEES SETS SEWN SHED SHIN SHUT SIGH SILK SILL
SINK SINS SIPS SITS SKID SKIM SKIP SKIS SLAB SLAM
SLAP SLED SLEW SLID SLIM SLIP SLIT SLOT SLUG SMOG
SNAG SNAP SNIP SNOB SNUG SOAK SOAR SOBS SOCK SODA
SOFA SOLD SOLE SOLO SONS SOOT SORE SOUL SOUR SOWN
SPAN SPAR SPAS SPED SPIN SPIT SPUN SPUR STAB STAG
STEM STEW STIR STOW STUB STUN SUCH SUDS SUED SUES
SUMS SUNG SUNK SUNS SWAB SWAM SWAN SWAP SWAY TABS
TACK TACO TACT TAGS TAME TANK TAPE TAPS TART TAUT
TAXI TEAL TEAR TEAS TEEN TENS TERM THAN THAT THAW
THEM THEN THEY THIS THUD TICK TIDY TIED TIER TIES
TILE TILL TILT TINT TIPS TIRE TOAD TOES TOFU TOIL
TOLD TOLL TOMB TONE TONS TOOK TOPS TORE TORN TOSS
TOTE TOUR TOWS TOYS TRAM TRAP TRAY TREK TRIM TRIO
TROT TUBA TUBE TUBS TUCK TUGS TUNA TUNE TUSK TWIG
UGLY UNDO UNTO UPON URGE URNS USED USER USES VAIN
VANE VANS VASE VEAL VEIL VEIN VENT VERB VEST VETO
VIAL VICE VINE VISA VOID VOWS WADE WAGE WAGS WAIL
WAKE WAND WANE WANT WARD WARE WARN WARP WARS WART
WARY WASP WAYS WEAK WEBS WEED WEEP WELD WENT WEPT
WERE WHAT WHEN WHIM WHIP WHIZ WHOM WICK WIGS WINS
WIPE WIRE WITH WITS WOKE WOLF WOMB WORE WORM WORN
WOVE WRAP WREN YAWN YELL YOGA YOLK YOUR ZEAL ZEST
ZINC ZOOM
`);

/* ---------------------------------------------------------------- 5 letters */

export const ANSWERS_5 = bank(`
ABOUT ABOVE ACTOR ADMIT ADOPT AFTER AGAIN AGENT AGREE AHEAD
ALARM ALBUM ALERT ALIKE ALIVE ALLOW ALONE ALONG ANGEL ANGER
ANGLE ANKLE APPLE APRON ARENA ARGUE ARISE ARROW ASIDE AVOID
AWAKE AWARD AWARE BADGE BAKER BASIC BEACH BEGIN BELOW BENCH
BERRY BIRTH BLACK BLADE BLAME BLANK BLAST BLAZE BLEND BLINK
BLOCK BLOOD BLOOM BOARD BONUS BOOST BOOTH BOUND BRAIN BRAND
BRAVE BREAD BREAK BRICK BRIDE BRIEF BRING BROAD BROOM BROWN
BRUSH BUILD BUNCH BURST BUYER CABIN CABLE CANDY CARGO CARRY
CATCH CAUSE CHAIN CHAIR CHALK CHARM CHART CHASE CHEAP CHECK
CHEEK CHEER CHESS CHEST CHIEF CHILD CHILL CHOIR CHORE CIVIL
CLAIM CLASS CLEAN CLEAR CLERK CLICK CLIFF CLIMB CLOCK CLOSE
CLOTH CLOUD COACH COAST COLOR COMET CORAL COUCH COUGH COUNT
COURT COVER CRACK CRAFT CRANE CRASH CREAM CRIME CROSS CROWD
CROWN CURVE CYCLE DAILY DAIRY DANCE DEATH DELAY DEPTH DIARY
DIRTY DOUBT DOZEN DRAFT DRAIN DRAMA DREAM DRESS DRIFT DRILL
DRINK DRIVE EAGER EAGLE EARLY EARTH EIGHT ELBOW EMPTY ENEMY
ENJOY ENTER EQUAL ERROR EVENT EVERY EXACT EXTRA FAITH FALSE
FANCY FAULT FAVOR FEAST FENCE FEVER FIBER FIELD FIFTY FIGHT
FINAL FIRST FLAME FLASH FLEET FLESH FLOAT FLOCK FLOOD FLOOR
FLOUR FLUID FOCUS FORCE FORGE FORTH FORTY FOUND FRAME FRESH
FRONT FROST FRUIT FUNNY GHOST GIANT GLASS GLOBE GLORY GLOVE
GRACE GRADE GRAIN GRAND GRANT GRAPE GRASP GRASS GREAT GREEN
GREET GRILL GROUP GUARD GUESS GUEST GUIDE HABIT HAPPY HEART
HEAVY HELLO HONEY HONOR HORSE HOTEL HOUSE HUMAN HUMOR HURRY
IMAGE INDEX INNER INPUT ISSUE JELLY JEWEL JOINT JUDGE JUICE
KNEEL KNIFE KNOCK LABEL LARGE LAUGH LAYER LEARN LEAST LEAVE
LEGAL LEMON LEVEL LIGHT LIMIT LOCAL LOGIC LOOSE LOWER LOYAL
LUCKY LUNCH MAGIC MAJOR MAPLE MARCH MATCH MAYBE MAYOR MEDAL
MEDIA MELON MERCY MERGE MERIT METAL METER MIGHT MINOR MINUS
MODEL MONEY MONTH MORAL MOTOR MOUNT MOUSE MOUTH MOVIE MUSIC
NERVE NEVER NIGHT NOBLE NOISE NORTH NOVEL NURSE OCCUR OCEAN
OFFER OFTEN OLIVE ONION ORBIT ORDER OTHER OUGHT OUTER OWNER
PAINT PANEL PAPER PARTY PATCH PAUSE PEACE PEACH PEARL PENNY
PHASE PHONE PHOTO PIANO PIECE PILOT PITCH PIZZA PLACE PLAIN
PLANE PLANT PLATE PLAZA POINT POWER PRESS PRICE PRIDE PRIME
PRINT PRIZE PROOF PROUD PROVE PUPIL QUEEN QUICK QUIET QUOTE
RADIO RAISE RANCH RANGE RAPID RATIO REACH REACT READY REBEL
REFER RELAX REPLY RIGHT RIVAL RIVER ROAST ROBIN ROBOT ROCKY
ROUGH ROUND ROUTE ROYAL RURAL SADLY SALAD SAUCE SCALE SCARE
SCENE SCOPE SCORE SCOUT SEVEN SHADE SHAKE SHALL SHAPE SHARE
SHARP SHEEP SHEET SHELF SHELL SHIFT SHINE SHIRT SHOCK SHORE
SHORT SHOUT SIGHT SILLY SINCE SIXTY SKILL SLEEP SLICE SLIDE
SMALL SMART SMELL SMILE SMOKE SNACK SNAKE SOLAR SOLID SOLVE
SORRY SOUND SOUTH SPACE SPARE SPARK SPEAK SPEED SPELL SPEND
SPICE SPINE SPLIT SPOON SPORT SQUAD STAFF STAGE STAIR STAMP
STAND START STATE STEAM STEEL STICK STILL STONE STORE STORM
STORY STOVE STRAW STRIP STUDY STUFF STYLE SUGAR SUNNY SUPER
SWEEP SWEET TABLE TASTE TEACH THANK THEME THICK THING THINK
THREE THUMB TIGER TIGHT TIRED TITLE TODAY TOKEN TOOTH TOPIC
TOTAL TOUCH TOUGH TOWEL TOWER TRACK TRADE TRAIL TRAIN TREAT
TREND TRIAL TRICK TRUCK TRUST TRUTH TWICE UNCLE UNDER UNION
UNITE UNTIL UPPER URBAN USUAL VALUE VIDEO VISIT VITAL VOCAL
VOICE WAGON WASTE WATCH WATER WHEAT WHEEL WHERE WHICH WHILE
WHITE WHOLE WIDTH WOMAN WORLD WORRY WORTH WOUND WRIST WRITE
WRONG YOUNG YOUTH
`);

/* rarer-but-fair words for the hard tier — disjoint from ANSWERS_5 */
export const ANSWERS_5_RARE = bank(`
ABYSS ADAGE ADEPT ADOBE AGILE AGONY AISLE ALGAE ALIBI ALOOF
AMBER AMEND AMPLE ANGST ANVIL AROMA ASKEW ATLAS ATTIC AUDIT
AZURE BALMY BANJO BARGE BASIL BATON BAYOU BEIGE BIRCH BISON
BLEAK BLURB BLUSH BOGUS BRAWL BRINE BRISK BROTH BUDGE BULKY
CACHE CAMEO CARAT CEDAR CELLO CHANT CHIDE CHIRP CHUNK CIDER
CINCH CLAMP CLEAT CLING CLOAK CLOVE COBRA COCOA COUPE COVET
COWER CRAVE CREED CREPE CRISP CROAK CRUMB CUMIN CYNIC DECAL
DECOY DEITY DELTA DENIM DEPOT DINGY DITTO DOWRY DROLL DRONE
DWELL EBONY EDICT EERIE ELUDE EMBER ENVOY EPOCH ETHIC ETHOS
EVOKE EXERT EXILE FABLE FEIGN FERAL FJORD FLAIR FLANK FLINT
FLORA FORAY FRAIL FROND FROTH FUDGE GAUDY GAUGE GAUNT GAVEL
GECKO GENRE GIDDY GLADE GLEAM GNOME GOUGE GRAVY GRIME GROVE
GUSTO HASTE HAVOC HEIST HERON HINGE HOIST HUMID HUSKY HYENA
ICING IDIOM IGLOO INEPT INFER IRONY IVORY JAUNT JUMBO KAYAK
KHAKI KIOSK KNACK KNOLL LANKY LAPEL LARVA LATCH LEDGE LEECH
LEMUR LILAC LIMBO LITHE LLAMA LOFTY LUNAR LURCH LYRIC MACAW
MANIA MARSH MAUVE MEDIC MIMIC MIRTH MOIST MOLAR MOOSE MORPH
MOSSY MOTIF MOTTO MULCH MURAL MUSTY NICHE NOMAD NUDGE NYMPH
OASIS OMEGA ONSET OPTIC OTTER OUNCE OZONE PARKA PATIO PECAN
PERCH PESTO PETAL PIVOT PLAID PLANK PLUCK PLUMB PLUME POISE
POLKA POSSE PRANK PREEN PROSE PROWL PRUNE PSALM QUAIL QUALM
QUART QUASH QUELL QUERY QUEUE QUILL QUILT QUIRK RABID RADAR
RASPY RAVEN REALM REGAL RELIC RHYME RIDGE ROGUE ROOST ROTOR
ROWDY SALVE SATIN SAUNA SAVVY SCALD SCARF SCONE SCOWL SCRUB
SEDAN SEPIA SERUM SHARD SHEEN SHREW SHRUB SIEGE SILKY SINEW
SKIFF SLANG SLATE SLEEK SLOTH SMIRK SNARE SNEER SNOUT SONAR
SPASM SPAWN SPRIG SQUID STAID STALE STARK STEED STOIC STOMP
STRUT SUAVE SUEDE SURGE SWIRL SYRUP TABOO TALON TANGO TAPIR
TAUNT TAWNY TEMPO TENOR TEPID THORN THYME TIARA TONIC TOPAZ
TOTEM TOXIN TROVE TRUCE TULIP TUNIC TWEED TWINE UDDER USHER
VALOR VAPOR VAULT VENOM VERGE VIGIL VIGOR VINYL VIPER VIVID
VODKA VOUCH VOWEL WAFER WALTZ WHARF WHIFF WHISK WINCE WITTY
YACHT YEARN ZEBRA ZESTY
`);

export const EXTRA_5 = bank(`
ABIDE ACORN ACUTE ADORE AGING ALOUD AMISS AMONG AMUSE APART
APPLY ARMOR ASSET AWAIT AWOKE BASIS BATCH BATHE BEADS BEANS
BEARS BEGAN BEGUN BEING BELLS BIRDS BLAND BLESS BLIMP BLIND
BLISS BLOAT BLUNT BOAST BOATS BONES BOOKS BOOTS BOSSY BOUGH
BOWLS BOXER BRAID BRAKE BRAVO BREED BRIBE BROIL BROKE BROOK
BUILT BULGE BUMPY BUNNY CAKES CALLS CAMPS CANAL CARDS CARES
CARVE CASES CAVES CEASE CENTS CHAOS CHEAT CHEWY CHIPS CHOKE
CHORD CHOSE CLASH CLONE CLOWN COATS CODES COINS COMFY CONCH
COOKS CORDS CORES COSTS CRABS CRATE CRAZE CREAK CREEK CREST
CROPS CROWS CRUDE CRUEL CRUSH CUBES CUBIC CURLY CURRY CURSE
DAISY DANDY DATES DEALS DEBIT DECAY DECKS DEEDS DESKS DEUCE
DIGIT DINER DITCH DIVER DODGE DOING DONOR DOORS DOUGH DRANK
DREAD DRIED DROPS DROVE DRUMS DRYER DUCKS DUNES DUSTY DWARF
EATEN EDGES ELDER ELECT ELITE EQUIP ERASE ERUPT ESSAY EVADE
EXCEL EXPEL FACES FACTS FAINT FAIRY FALLS FARMS FATAL FEARS
FEEDS FEELS FETCH FEWER FIERY FILES FILMS FILTH FINDS FIRES
FIRMS FLAGS FLAKE FLARE FLASK FLICK FLIES FLING FLOWS FLUFF
FLUKE FLUNG FLUSH FLUTE FOAMY FOGGY FOLDS FOODS FOOLS FORGO
FORKS FORMS FORTS FORUM FOYER FRIED FRISK FROGS FUELS FUZZY
GAMES GATES GIFTS GIRLS GIVEN GLARE GLAZE GLIDE GLINT GLOOM
GLOSS GOALS GOATS GOOEY GRABS GRAZE GREED GRIEF GRINS GRIPS
GROAN GROWL GRUFF GRUNT GUAVA GULLY GUPPY HAIKU HALLS HANDS
HANDY HARSH HATCH HAUNT HAZEL HEADS HEARS HEATS HEDGE HEFTY
HENCE HERBS HIDES HILLS HILLY HINTS HOBBY HOLDS HOLES HOLLY
HOMES HOOKS HOPES HORNS HOSTS HOUND HOURS HOVER HUNCH HUNTS
HUTCH ICONS IDEAS INBOX INERT ITCHY ITEMS JOINS JOKER JOKES
JOLLY JUICY JUMPS KARMA KEEPS KICKS KINGS KITES KNEAD KNEES
KNELT KNOTS KNOWS LADLE LAKES LAMPS LANDS LANES LASSO LEADS
LEAKY LEAPT LEASE LEASH LEVER LIKEN LIKES LIMBS LINEN LINER
LINES LINKS LIONS LISTS LIVER LOADS LOANS LOBBY LOCKS LODGE
LOGIN LOOKS LOOPS LORDS LOVES LUMPY LUNGE MADAM MAGMA MAILS
MAKES MAMBO MANGO MANOR MARKS MARRY MASKS MASON MEALS MEANT
MEETS MELTS MENUS MERRY MESSY METRO MILES MILLS MINCE MINDS
MINER MINES MINTY MISTY MOCHA MODEM MODES MOGUL MOLES MONKS
MOODS MOODY MOONS MOTEL MOUND MOURN MOVES MOWER MUDDY MUMMY
MUNCH MUSHY MYTHS NAILS NAMES NANNY NASAL NASTY NAVAL NECKS
NEEDS NEEDY NEIGH NESTS NEWER NIFTY NINJA NINTH NODES NOISY
NOSES NOTCH NOTES NOUNS NUTTY OATHS OCTET ODDLY OLDER OPERA
ORGAN OVERT OWING OXIDE PACKS PAGES PAINS PAIRS PALMS PANDA
PANIC PANSY PARKS PARTS PASTA PASTE PATHS PATTY PAYEE PEAKS
PEARS PEDAL PENNE PERKY PESKY PHONY PICKS PICKY PIETY PIGGY
PILAF PILES PILLS PINCH PINES PINKY PIOUS PIPES PIXEL PIXIE
PLANS PLAYS PLOTS PLUGS PLUMP PLUSH POACH POEMS POETS POLAR
POLES POLYP PONDS POOLS POPPY PORTS POSTS POUCH POUND PRAWN
PRIOR PRISM PRIVY PROBE PROMO PRONE PRONG PROXY PRUDE PUFFY
PULLS PULPY PUMPS PUNCH PUREE PURSE PUSHY PUTTY QUACK QUAKE
QUARK QUEST QUOTA RACES RAILS RAINS RAINY RALLY RANKS RATES
RAYON READS REEDY REHAB REIGN RELAY REPAY RERUN RESIN RESTS
RETRO RHINO RIDES RINGS RINSE RIPEN RISEN RISES RISKS ROADS
ROAMS ROBES ROCKS ROLES ROLLS ROOFS ROOMS ROOMY ROOTS ROPES
ROSES ROUGE ROUSE ROVER RUDDY RUGBY RUINS RULES RUMBA RUMOR
RUPEE SAILS SAINT SALES SALSA SALTY SANDS SANDY SASSY SAUTE
SAVES SCENT SCOFF SCOLD SCOOP SCOOT SCORN SCRAM SEALS SEATS
SEEDS SEEDY SEEKS SEIZE SELLS SENDS SENSE SEVER SEWER SHACK
SHAFT SHAKY SHAME SHAWL SHEAR SHIPS SHOES SHONE SHOOK SHOPS
SHOVE SHOWS SHOWY SHRED SHRUG SHUSH SHYLY SIDES SIGNS SINGE
SINGS SINKS SITES SIXTH SIZES SKATE SKIER SKIES SKIMP SKINS
SKIRT SKULL SLACK SLANT SLASH SLEET SLICK SLIME SLIMY SLING
SLIPS SLOPE SLOSH SLOTS SLUMP SLUNG SLUSH SMACK SMASH SMEAR
SMITH SMOCK SMOKY SNAIL SNAPS SNARL SNEAK SNIDE SNIFF SNORE
SNOWY SOAPY SOBER SOGGY SONGS SOOTY SORTS SOULS SOUPS SOUPY
SPADE SPANS SPICY SPIKE SPILL SPINS SPIRE SPITE SPLAT SPOIL
SPOKE SPOOK SPOOL SPORE SPOTS SPOUT SPRAY SPREE SPURT SQUAT
STAIN STAKE STALK STALL STARE STARS STASH STAYS STEAK STEAL
STEEP STEER STEMS STEPS STINT STIRS STOKE STOLE STONY STOOD
STOOL STOOP STOPS STOUT STRAP STRAY STRUM STUCK STUMP STUNG
STUNT SUITS SULKY SURLY SUSHI SWAMP SWANS SWARM SWEAT SWEPT
SWIFT SWIMS SWING SWOOP SWORD SWORE TABBY TACKY TAFFY TAILS
TAKES TALES TALKS TALLY TANGY TANKS TAPES TARDY TASKS TEAMS
TEARS TEASE TEDDY TELLS TEMPT TENSE TENTS TENTH TERMS TERSE
TESTS TEXTS THEFT THIGH THREW THROB THROW THUMP TIDES TILES
TIMES TIMID TIPSY TIRES TOADS TOAST TONAL TOOLS TORSO TOURS
TOWNS TOXIC TRACE TRAPS TRAWL TRAYS TREAD TREES TRIBE TRIPS
TRITE TROLL TROOP TROUT TRUNK TUBES TUMMY TUNER TUNES TURBO
TURNS TUTOR TWANG TWEAK TWEET TWINS TWIRL TWIST TYPES UNCUT
UNDID UNDUE UNFIT UNITS UNITY UNTIE UNZIP UPSET USAGE USERS
UTTER VAGUE VALET VALVE VEGAN VEILS VEINS VENUE VERBS VERSE
VIEWS VINES VISOR VISTA VIXEN VOGUE VOTES VYING WACKY WAGES
WAIST WAITS WAIVE WALKS WALLS WANTS WARDS WAVES WEARY WEAVE
WEDGE WEEDS WEEKS WEIGH WELLS WHALE WHINE WHIRL WHIPS WHOSE
WIDEN WIDOW WIELD WINDS WINDY WINES WINGS WIRES WISER WITCH
WOKEN WOOZY WORDS WORKS WORMS WORSE WORST WOVEN WRECK WRING
YARDS YEARS YEAST YIELD YODEL YUMMY ZILCH ZIPPY ZONES
`);

/* ---------------------------------------------------------------- 6 letters */

export const ANSWERS_6 = bank(`
ACCEPT ACTION ACTIVE ADVICE AGENCY ALMOST ALWAYS AMOUNT ANIMAL ANSWER
ANYONE APPEAR AROUND ARRIVE ARTIST ATTACK AUTUMN BASKET BATTLE BEAUTY
BECOME BEFORE BEHIND BELIEF BELONG BETTER BEYOND BORDER BOTTLE BOTTOM
BRANCH BREATH BRIDGE BRIGHT BROKEN BUDGET BURDEN BUTTON CAMERA CANCEL
CANDLE CANVAS CARBON CAREER CASTLE CENTER CHANCE CHANGE CHARGE CHOICE
CHOOSE CHURCH CIRCLE CLEVER CLIENT CLOSET COFFEE COLUMN COMBAT COMMON
COPPER CORNER COTTON COUPLE COUSIN CREATE CREDIT CRISIS CUSTOM DAMAGE
DANGER DEBATE DECADE DECIDE DEFEAT DEFEND DEGREE DEMAND DESERT DESIGN
DETAIL DEVICE DINNER DIRECT DOCTOR DOLLAR DOMAIN DOUBLE DRAGON DRAWER
DRIVER DURING EFFECT EFFORT EIGHTY EITHER ELEVEN EMPIRE ENERGY ENGINE
ENOUGH ENTIRE ESCAPE ESTATE EXCUSE EXPAND EXPECT EXPERT EXPORT EXTEND
FABRIC FAMILY FAMOUS FARMER FATHER FIGURE FINGER FINISH FLIGHT FLOWER
FOLLOW FOREST FORGET FORMAL FORMER FOURTH FREEZE FRIDGE FRIEND FROZEN
FUTURE GARAGE GARDEN GATHER GENTLE GLOBAL GOLDEN GROUND GROWTH GUITAR
HAMMER HANDLE HAPPEN HARBOR HEALTH HEIGHT HIDDEN HOLLOW HONEST HUNGRY
IGNORE IMPACT IMPORT INCOME INDEED INDOOR INJURY INSECT INSIDE INTENT
INVEST INVITE ISLAND JACKET JUNGLE JUNIOR KITTEN LADDER LAUNCH LAWYER
LEADER LEAGUE LEGEND LENGTH LESSON LETTER LIKELY LIQUID LISTEN LITTLE
LIVING LONELY LUXURY MANAGE MARBLE MARGIN MARKET MASTER MATTER MEADOW
MEDIUM MEMBER MEMORY METHOD MIDDLE MINUTE MIRROR MOBILE MODERN MOMENT
MONKEY MOTHER MOTION MUSCLE MUSEUM NARROW NATION NATURE NEARBY NEEDLE
NEPHEW NORMAL NOTICE NUMBER OBJECT OBTAIN OFFICE ONLINE OPTION ORANGE
ORIGIN OUTPUT OXYGEN PALACE PARENT PENCIL PEOPLE PEPPER PERIOD PERMIT
PERSON PICKLE PICNIC PIGEON PILLOW PLANET PLEASE PLENTY POCKET POETRY
POLICE POLICY POLISH POTATO POWDER PRAISE PRAYER PREFER PRETTY PRINCE
PRISON PROFIT PROPER PUBLIC PUPPET PURPLE PURSUE PUZZLE RABBIT RANDOM
RATHER REASON RECALL RECENT RECIPE RECORD REDUCE REFORM REFUSE REGION
REGRET RELIEF REMAIN REMIND REMOTE REMOVE REPAIR REPEAT REPORT RESCUE
RESORT RESULT RETIRE RETURN REVEAL REVIEW REWARD RHYTHM RIBBON ROCKET
ROTTEN RUBBER SAFETY SALARY SAMPLE SCHEME SCHOOL SCREEN SCRIPT SEARCH
SEASON SECOND SECRET SECTOR SECURE SELECT SENIOR SETTLE SHADOW SHOWER
SIGNAL SILENT SILVER SIMPLE SINGER SINGLE SISTER SKETCH SLIGHT SMOOTH
SOCCER SOCIAL SOURCE SPEECH SPIDER SPIRIT SPRING SQUARE STABLE STATUE
STATUS STEADY STOLEN STREAM STREET STRESS STRIKE STRING STRONG STUDIO
SUBMIT SUDDEN SUMMER SUMMIT SUNSET SUPPLY SURVEY SWITCH SYMBOL SYSTEM
TALENT TARGET TEMPLE TENDER THEORY THIRTY THREAD THREAT THRONE TICKET
TIMBER TISSUE TOMATO TONGUE TOWARD TRAVEL TREATY TRIPLE TROPHY TUNNEL
TURTLE TWELVE TWENTY UNIQUE UPDATE UPWARD URGENT USEFUL VALLEY VELVET
VENDOR VICTIM VIOLIN VIRTUE VISION VOLUME VOYAGE WALLET WALNUT WEALTH
WEAPON WEEKLY WEIGHT WINDOW WINNER WINTER WISDOM WITHIN WIZARD WONDER
WOODEN YELLOW
`);

export const EXTRA_6 = bank(`
ACCESS ACROSS ADJUST ADMIRE ADVISE AFFAIR AFFORD AFRAID AGENDA ASSIST
ASSUME ATTEND AVENUE BAKERY BANNER BEACON BEHAVE BESIDE BEWARE BISHOP
BLOUSE BORROW BOUNCE BREEZE BRUNCH BUBBLE BUCKET BUNDLE BUTTER CACTUS
CASINO CELLAR CEMENT CHAIRS CHERRY CHOSEN CIRCUS COBALT COCOON COMEDY
CONVEY COSMOS CRADLE CRAYON CRUNCH DAZZLE DECENT DEFINE DELETE DEPEND
DEPUTY DEVOTE DONKEY DRENCH EASILY EDIBLE EMPLOY ENABLE ENGAGE ENROLL
ENSURE EQUITY EXCEED EXCESS EXOTIC FALCON FEEBLE FELLOW FIERCE FILTER
FLAVOR FORBID FOSSIL FROLIC GADGET GALAXY GENIUS GENTLY GLANCE GOBLIN
GOSSIP GOVERN GRUMPY HAZARD HELMET HERMIT HICCUP HUMBLE HUSTLE IGUANA
IMPOSE INFANT INFORM INHALE INJECT INSIST INTAKE INVENT JAGUAR JERSEY
JIGSAW JOCKEY JOYFUL KERNEL KETTLE KINDLY KNIGHT LAGOON LAVISH LENTIL
LIZARD LOCATE LOCKER LOTION LUMBER MAGNET MAIDEN MAMMAL MANNER MANTLE
MARROW MASCOT MEDDLE MELLOW MELODY MENTOR MIDDAY MINGLE MITTEN MODEST
MODIFY MORSEL MOSAIC MUFFIN MYSTIC NAPKIN NEATLY NECTAR NIBBLE NICKEL
NOODLE NOTIFY NOVICE NUANCE NUGGET OBLIGE OCCUPY OPPOSE ORCHID ORDEAL
ORNATE OUTFIT OUTLET OYSTER PADDLE PANTRY PARADE PARROT PASTEL PEBBLE
PHRASE PICKET PIRATE PLAQUE PLEDGE PLUNGE POLLEN PONDER POSTER POUNCE
PREACH PUDDLE PURITY QUAINT QUENCH QUIVER RADISH RAGGED RAISIN RANGER
RASCAL RAVINE RECKON REFUND RELISH REMEDY RENDER RESUME REVOLT RIDDLE
RIPPLE ROBUST RODENT RUFFLE RUSTIC SADDLE SAFARI SAILOR SALMON SAVORY
SCARCE SCRAPE SCRIBE SEQUEL SERENE SHIELD SHIVER SHOVEL SHRIMP SHRINE
SHRINK SIMMER SIPHON SKATER SLIVER SLOGAN SNEEZE SOLEMN SONNET SOOTHE
SPHERE SPIRAL SPLASH SPRAIN SPROUT SQUASH SQUEAK SQUEAL STANZA STAPLE
STARCH STENCH STITCH STRIDE STRIPE STRIVE STROLL SUBTLE SUBURB SUMMON
SUNDAE SUPERB SWEATY SWERVE TABLES TACKLE TAILOR TANDEM TANGLE TATTOO
TAVERN TEAPOT TEMPER THIRST THRIVE TICKLE TIGERS TINGLE TIPTOE TITLES
TOGGLE TOKENS TOWELS TOWERS TRACKS TRADES TRAILS TRAINS TREATS TREMOR
TRENCH TRENDS TRIALS TRICKS TRIVIA TRUCKS TRUTHS TUMBLE TUNDRA TURNIP
TUXEDO UNFOLD UNISON UPBEAT UPHILL UPROAR URCHIN USABLE UTMOST VACANT
VACUUM VALUES VANISH VERIFY VESSEL VIABLE VIDEOS VISITS VOICES WAGONS
WALRUS WANDER WATERS WEASEL WHEELS WHOLLY WICKED WIGGLE WINTRY WOBBLE
WOMBAT WRENCH YOGURT YONDER ZENITH ZIGZAG ZIPPER ZODIAC
`);

/* ---------------------------------------------------------------- 7 letters */

export const ANSWERS_7 = bank(`
ABILITY ABSENCE ACCOUNT ACHIEVE ADDRESS ADVANCE AGAINST AIRPORT ALREADY AMAZING
ANCIENT ANOTHER ANYBODY ARRANGE ARTICLE ATTEMPT ATTRACT AVERAGE AWESOME BALANCE
BALCONY BANQUET BARGAIN BATTERY BEDROOM BELIEVE BENEATH BENEFIT BETWEEN BICYCLE
BLANKET BLOSSOM BROTHER CABBAGE CABINET CAPITAL CAPTAIN CAPTURE CAREFUL CARTOON
CENTURY CERTAIN CHAMBER CHANNEL CHAPTER CHARITY CHICKEN CIRCUIT CLASSIC CLIMATE
COLLECT COLLEGE COMBINE COMFORT COMMAND COMMENT COMPANY COMPARE COMPETE COMPLEX
CONCEPT CONCERN CONCERT CONDUCT CONFIRM CONNECT CONTACT CONTAIN CONTENT CONTEST
CONTROL CORRECT COTTAGE COUNCIL COUNTRY COURAGE CRYSTAL CULTURE CURIOUS CURRENT
CUSHION DELIGHT DELIVER DESSERT DESTINY DEVELOP DIAMOND DIGITAL DISPLAY DOLPHIN
ECONOMY EDITION ELEGANT ELEMENT EMBRACE EMOTION EMPEROR EXAMPLE EXHIBIT EXPLAIN
EXPLORE EXPRESS EXTREME FACTORY FAILURE FANTASY FASHION FEATURE FICTION FIFTEEN
FITNESS FOREVER FORTUNE FORWARD FREEDOM FURTHER GALLERY GENERAL GENUINE GLACIER
GRAVITY GROCERY HABITAT HARVEST HEALTHY HIGHWAY HISTORY HOLIDAY HORIZON HUSBAND
IMAGINE IMPROVE INCLUDE INSTALL INSTANT INSTEAD JOURNAL JOURNEY JUSTICE KITCHEN
LANTERN LAUNDRY LEATHER LECTURE LIBRARY LICENSE MACHINE MANAGER MASSIVE MAXIMUM
MEASURE MEDICAL MESSAGE MINERAL MINIMUM MIRACLE MISSION MISTAKE MIXTURE MONITOR
MONSTER MORNING MUSTARD MYSTERY NATURAL NETWORK NOTHING OBVIOUS OCTOPUS OFFICER
OPINION ORGANIC OUTDOOR OUTSIDE PACKAGE PAINTER PANCAKE PARTNER PASSAGE PASSION
PATIENT PATTERN PAYMENT PENALTY PERFECT PERFORM PERHAPS PICTURE PIONEER PLASTIC
POPCORN POPULAR PREDICT PREMIUM PREPARE PRESENT PREVENT PRIMARY PRIVACY PRIVATE
PROBLEM PROCESS PRODUCE PRODUCT PROGRAM PROJECT PROMISE PROTECT PROVIDE PURPOSE
PYRAMID QUALIFY QUALITY QUARTER RAINBOW REALITY RECEIPT RECEIVE RECOVER REFLECT
REGULAR RELEASE REPLACE REQUEST REQUIRE RESERVE RESPECT RESPOND RESTORE ROUTINE
SAUSAGE SCIENCE SECTION SERIOUS SERVICE SEVENTY SHELTER SILENCE SIMILAR SOCIETY
SOLDIER SOMEHOW SPECIAL SPONSOR STATION STOMACH STORAGE STRANGE STRETCH STUDENT
SUBJECT SUCCESS SUGGEST SUPPORT SUPPOSE SUPREME SURFACE SURGERY SUSPECT TEACHER
THEATER THERAPY THOUGHT THUNDER TONIGHT TOURIST TRAFFIC TRIUMPH TROUBLE TYPICAL
UNKNOWN UPGRADE UTILITY VARIETY VEHICLE VENTURE VERSION VICTORY VILLAGE VINTAGE
VISITOR VOLCANO WEATHER WEBSITE WEEKEND WELCOME WESTERN WHISPER WITNESS
`);

export const EXTRA_7 = bank(`
ABANDON ACROBAT ADMIRAL ALGEBRA AMBIENT ANSWERS ANTENNA APPLAUD APRICOT AQUATIC
ARCHERY ARTISTS AUCTION AVOCADO AWKWARD BAGGAGE BANDAGE BASKETS BATTLES BEDTIME
BEEHIVE BISCUIT BONFIRE BORDERS BOTTLES BOULDER BOUQUET BRACKET BRAVERY BREWERY
BRIDGES BUFFALO BUTTONS BUZZARD CALCIUM CAMERAS CANDLES CARAVAN CASCADE CASTLES
CATALOG CEILING CENTERS CHANCES CHANGES CHARIOT CHEDDAR CHIMNEY CHOICES CHOWDER
CIRCLES CLARIFY CLARITY CLIENTS CLIMBER COLUMNS COMPASS COMPOST CONCEAL CONFESS
CONFUSE CONQUER CONSOLE CONSUME CONTOUR CORNERS CORRUPT COSTUME COUPLES COUSINS
CRACKLE CRICKET CRUMBLE CUISINE CUPCAKE CUSTARD CYCLONE CYPRESS DEBATES DECADES
DECLARE DEFAULT DEFROST DEGREES DENSITY DESERTS DESIGNS DETAILS DEVICES DIAGRAM
DICTATE DIGNITY DILEMMA DINNERS DIPLOMA DISCUSS DISEASE DISMISS DISTANT DIVERSE
DOCTORS DOLLARS DRAGONS DRAWERS DRIVERS DRIZZLE DROUGHT DUCHESS EARNEST ECLIPSE
EFFECTS EFFORTS ELEVATE EMBASSY EMERALD ENCHANT ENDLESS ENGINES EPISODE ESCAPES
ESSENCE ESTATES ETERNAL EVENING EXAMINE EXCUSES EXHAUST EXPENSE EXPERTS EXPLODE
EYEBROW FABRICS FARMERS FATHERS FEATHER FERMENT FESTIVE FIGURES FINGERS FIREFLY
FISHERY FLANNEL FLIGHTS FLOWERS FLUTTER FOOTAGE FORESTS FRAGILE FRECKLE FREIGHT
FRIENDS FURNACE FUTURES GARDENS GAZELLE GENERIC GESTURE GLIMMER GLIMPSE GLISTEN
GLITTER GLUCOSE GONDOLA GORILLA GRANITE GRIDDLE GRIZZLY GRUMBLE GUITARS HAIRCUT
HALLWAY HAMMERS HAMMOCK HAMSTER HANDFUL HANDLES HARBORS HARMONY HATCHET HEATHER
HEIGHTS HEXAGON HOWEVER HUNDRED HYDRANT ICEBERG IMPULSE INCLINE INDULGE INHERIT
INQUIRE INSECTS INSPIRE ISLANDS ISOLATE JACKETS JANITOR JASMINE JAVELIN JEALOUS
JUKEBOX JUNGLES KEYHOLE KINGDOM KITTENS LADDERS LADYBUG LASAGNA LAWYERS LEADERS
LEAGUES LEGENDS LENGTHS LEOPARD LESSONS LETTERS LETTUCE LIBERTY LOBSTER LULLABY
MAGENTA MANSION MARKETS MASTERS MATTERS MEADOWS MEMBERS MERMAID METHODS MIGRATE
MILEAGE MILLION MINUTES MIRRORS MOLLUSK MOMENTS MONARCH MONKEYS MONSOON MOTHERS
MOTIONS MUFFLER MUSCLES MUSEUMS MUSTANG NATIONS NEEDLES NEPHEWS NERVOUS NOSTRIL
NOTICES NOWHERE NUMBERS NUMERAL NURSERY OBJECTS OBSCURE OBSERVE OCTAGON ODYSSEY
OFFICES OMELETS OPERATE OPTIONS ORANGES ORCHARD OREGANO ORIGINS OSTRICH OVATION
OVERLAP PADDOCK PAGEANT PALACES PANTHER PAPRIKA PARENTS PARSLEY PEACOCK PELICAN
PENCILS PENGUIN PERIODS PERMITS PERSIST PERSONS PICKLES PIGEONS PIGMENT PILGRIM
PILLOWS PINBALL PLANETS PLATEAU PLUMBER POCKETS PORTION POSSESS POTIONS PRAIRIE
PRECISE PRETZEL PREVIEW PRIMATE PRINCES PRISONS PROFITS PRONOUN PROSPER PROTEIN
PROVERB PUMPKIN PUPPETS PUZZLES QUANTUM QUIETLY RABBITS RACCOON RADIANT RAVIOLI
REALIZE REASONS RECIPES RECORDS RECYCLE REDWOOD REFEREE REFRESH REGIONS REPORTS
REPTILE RESULTS RETREAT REUNION REWARDS RHUBARB RIBBONS ROCKETS ROOSTER SAMPLES
SATCHEL SCARLET SCHOLAR SCHOOLS SCOOTER SCRATCH SCREENS SCRIPTS SEAGULL SEASONS
SECONDS SECRETS SECTORS SENIORS SHADOWS SHALLOW SHAMPOO SHERIFF SHOWERS SHUFFLE
SIGNALS SINGERS SISTERS SKEPTIC SLIPPER SMUGGLE SNORKEL SNUGGLE SOURCES SPARKLE
SPARROW SPATULA SPECIES SPIDERS SPINACH SPIRITS SPRINGS SQUARES SQUEEZE STADIUM
STAMINA STAPLER STARDOM STATUES STEEPLE STIRRUP STREAMS STREETS STRIKES STRINGS
STUDIOS SUCCEED SUMMITS SUNDIAL SUNRISE SUNSETS SURPLUS SURVEYS SWALLOW SYMBOLS
SYSTEMS TALENTS TANGENT TAPIOCA TARGETS TEMPEST TEMPLES TERRACE TEXTURE THIMBLE
THISTLE THREADS THREATS THRONES TICKETS TISSUES TOASTER TONGUES TORNADO TRACTOR
TRAMPLE TRAVELS TREMBLE TRUMPET TSUNAMI TUNNELS TURTLES TWISTER UKULELE UNICORN
UPRIGHT UTENSIL VACCINE VALLEYS VANILLA VARNISH VENDORS VETERAN VICTIMS VILLAIN
VINEGAR VIOLINS VIRTUES VISIONS VITAMIN VOLTAGE VOLUMES VULTURE WALLETS WALNUTS
WARRIOR WEAPONS WEEKDAY WHISTLE WILDCAT WINDOWS WINNERS WINTERS WITHOUT WIZARDS
WONDERS WORKOUT WRESTLE
`);

/* ------------------------------------------------------------ derived sets */

/** Statistically strong opening words (per length) used by the Starter assist. */
export const STARTERS: Record<number, string> = {
  4: 'RATE',
  5: 'RAISE',
  6: 'SAILOR',
  7: 'NOTICES'
};

export const ALLOWED_BY_LEN: Record<number, Set<string>> = {
  4: new Set([...ANSWERS_4, ...EXTRA_4]),
  5: new Set([...ANSWERS_5, ...ANSWERS_5_RARE, ...EXTRA_5]),
  6: new Set([...ANSWERS_6, ...EXTRA_6]),
  7: new Set([...ANSWERS_7, ...EXTRA_7])
};

/* ------------------------------------------------------------- validation */

/** Integrity checks for the banks — returns human-readable error strings. */
export function validateWordGuessBank(): string[] {
  const errors: string[] = [];

  const lists: Array<[name: string, words: string[], len: number]> = [
    ['answers-4', ANSWERS_4, 4],
    ['extra-4', EXTRA_4, 4],
    ['answers-5', ANSWERS_5, 5],
    ['answers-5-rare', ANSWERS_5_RARE, 5],
    ['extra-5', EXTRA_5, 5],
    ['answers-6', ANSWERS_6, 6],
    ['extra-6', EXTRA_6, 6],
    ['answers-7', ANSWERS_7, 7],
    ['extra-7', EXTRA_7, 7]
  ];

  for (const [name, words, len] of lists) {
    const seen = new Set<string>();
    for (const w of words) {
      if (!/^[A-Z]+$/.test(w)) errors.push(`${name}: "${w}" has characters outside A-Z`);
      if (w.length !== len) errors.push(`${name}: "${w}" is not ${len} letters`);
      if (seen.has(w)) errors.push(`${name}: duplicate "${w}"`);
      seen.add(w);
    }
  }

  // answer banks stay non-overlapping with their extras (keeps lists clean),
  // and the rare tier stays disjoint from the common tier
  const overlapChecks: Array<[string, string[], string, string[]]> = [
    ['answers-4', ANSWERS_4, 'extra-4', EXTRA_4],
    ['answers-5', ANSWERS_5, 'extra-5', EXTRA_5],
    ['answers-5-rare', ANSWERS_5_RARE, 'extra-5', EXTRA_5],
    ['answers-5', ANSWERS_5, 'answers-5-rare', ANSWERS_5_RARE],
    ['answers-6', ANSWERS_6, 'extra-6', EXTRA_6],
    ['answers-7', ANSWERS_7, 'extra-7', EXTRA_7]
  ];
  for (const [aName, a, bName, b] of overlapChecks) {
    const bSet = new Set(b);
    for (const w of a) if (bSet.has(w)) errors.push(`"${w}" appears in both ${aName} and ${bName}`);
  }

  // minimum sizes (per the game design)
  const sizes: Array<[string, number, number]> = [
    ['answers-4', ANSWERS_4.length, 120],
    ['answers-5', ANSWERS_5.length, 120],
    ['answers-5-rare', ANSWERS_5_RARE.length, 80],
    ['answers-6', ANSWERS_6.length, 80],
    ['answers-7', ANSWERS_7.length, 80],
    ['allowed-4', ALLOWED_BY_LEN[4].size, 300],
    ['allowed-5', ALLOWED_BY_LEN[5].size, 400],
    ['allowed-6', ALLOWED_BY_LEN[6].size, 200],
    ['allowed-7', ALLOWED_BY_LEN[7].size, 200]
  ];
  for (const [name, actual, min] of sizes) {
    if (actual < min) errors.push(`${name} has ${actual} words, needs at least ${min}`);
  }

  // every answer must be an accepted guess
  const answerBanks: Array<[string, string[], number]> = [
    ['answers-4', ANSWERS_4, 4],
    ['answers-5', ANSWERS_5, 5],
    ['answers-5-rare', ANSWERS_5_RARE, 5],
    ['answers-6', ANSWERS_6, 6],
    ['answers-7', ANSWERS_7, 7]
  ];
  for (const [name, words, len] of answerBanks) {
    for (const w of words) {
      if (!ALLOWED_BY_LEN[len].has(w)) errors.push(`${name}: "${w}" missing from allowed set`);
    }
  }

  // starter words must be legal guesses of the right length
  for (const [len, word] of Object.entries(STARTERS)) {
    const n = Number(len);
    if (word.length !== n) errors.push(`starter for length ${n} ("${word}") has wrong length`);
    if (!ALLOWED_BY_LEN[n]?.has(word)) errors.push(`starter "${word}" is not in the allowed set for length ${n}`);
  }

  return errors;
}
