import type { Difficulty } from '../../../platform/types';
import type { ArrowEntry, ArrowPuzzleDef, Dir } from './engine';
/**
 * Hand-authored arrow crosswords. The GRIDS were laid out with an offline
 * builder (row by row, every column kept a feasible prefix of a real word,
 * proven by `validateArrowPuzzle`); the CLUES are written by hand, one per
 * answer, in the terse register the small print of a clue cell asks for —
 * a cell with one clue holds up to 30 characters, a cell shared by a right
 * and a down clue holds 20 each (validate enforces both). Run
 * `npm run validate` after editing: it rebuilds every puzzle, checks all
 * crossings and accidental runs, and fails on an answer without a clue.
 *
 * An entry is [answer, row, col, dir] positioned by its FIRST letter; the
 * engine derives the clue cell one step before it. Words may recur across
 * puzzles and share their clue.
 */

/** answer -> clue (alphabetical) */
export const CLUES: Record<string, string> = {
  ABLE: 'Capable',
  ABUSE: 'Mistreat',
  ACTOR: 'Movie star',
  ADD: 'Sum up',
  ADULT: 'Grown-up',
  AKIN: 'Related',
  ALE: 'Pub pint',
  ALIKE: 'Similar',
  ALSO: 'In addition',
  AMEND: 'Revise',
  AMID: 'Among',
  ANT: 'Picnic pest',
  AORTA: 'Main artery',
  AREA: 'Region',
  AROMA: 'Pleasant smell',
  ARSON: 'Fire crime',
  ART: 'Gallery display',
  ASPECT: 'Facet',
  ATOP: 'On the summit of',
  ATTEMPT: 'Try',
  AVAIL: 'Be of use',
  AWFUL: 'Terrible',
  BAG: 'Sack',
  BAR: 'Pub',
  BARN: 'Hay store',
  BEAR: 'Honey lover',
  BED: 'Sleeping spot',
  BEE: 'Honey maker',
  BIG: 'Large',
  BOTTOM: 'Lowest part',
  BRAN: 'Cereal fiber',
  BRINE: 'Salty water',
  CAP: 'Brimmed hat',
  CARBON: 'Diamond element',
  CHEW: 'Work the jaws',
  CHOKE: 'Gag',
  CLAIM: 'Assert',
  CLEAR: 'Crystal-___',
  CLERK: 'Office worker',
  COMBAT: 'Fighting',
  COURAGE: 'Bravery',
  CRACK: 'Narrow split',
  CRONE: 'Old witch',
  CRY: 'Weep',
  CUE: 'Pool stick',
  CULTURE: 'Arts and customs',
  CURLY: 'Not straight',
  DAM: 'River barrier',
  DASH: 'Sprint',
  DEED: 'Act; title paper',
  DELAY: 'Postpone',
  DENT: 'Small dip',
  DIG: 'Excavate',
  DIN: 'Loud noise',
  DOT: 'Tiny spot',
  DOTE: 'Adore fondly',
  DRAGON: 'Fire-breather',
  EAGER: 'Keen',
  EAR: 'Hearing organ',
  EARL: 'British noble',
  EASE: 'Comfort',
  EATS: 'Has dinner',
  EBB: 'Flow back',
  EBONY: 'Black wood',
  ECHO: 'Canyon reply',
  EGO: 'Sense of self',
  EITHER: 'One or the other',
  ELDER: 'Senior',
  ELDEST: 'Oldest child',
  ELECT: 'Vote in',
  EMBERS: 'Fire\'s last glow',
  EMBODY: 'Be the image of',
  EMBRACE: 'Hug',
  EMIT: 'Give off',
  EMOTION: 'Feeling',
  EMU: 'Ostrich kin',
  END: 'Finish',
  EPIC: 'Grand tale',
  ERA: 'Period of time',
  ERASE: 'Rub out',
  ERECT: 'Upright',
  ERODE: 'Wear away',
  ESTATE: 'Large property',
  ESTEEM: 'High regard',
  ETCHED: 'Engraved',
  EVE: 'Night before',
  EVICT: 'Throw out',
  EWES: 'Female sheep',
  EXERCISE: 'Workout',
  EXIT: 'Way out',
  GAS: 'Petrol',
  GEM: 'Jewel',
  GENIAL: 'Friendly',
  GIN: 'Tonic\'s partner',
  GIZMO: 'Gadget',
  GOO: 'Sticky stuff',
  GOT: 'Obtained',
  GRAM: 'Tiny weight',
  GREW: 'Got bigger',
  GUSH: 'Pour out',
  HABITAT: 'Natural home',
  HAMMER: 'Nail driver',
  HARROW: 'Farm rake',
  HEAT: 'Warmth',
  HER: 'That woman\'s',
  HERE: 'In this place',
  HEY: 'Hi there!',
  HID: 'Kept out of sight',
  HINT: 'Clue',
  HOBBY: 'Pastime',
  HUSH: 'Quiet!',
  ICE: 'Frozen water',
  ICILY: 'Coldly',
  ICY: 'Frozen over',
  IMBUE: 'Fill with',
  INLET: 'Small bay',
  INPUT: 'Data fed in',
  IODINE: 'Tincture for cuts',
  IRE: 'Anger',
  ITCH: 'Scratchy urge',
  ITS: 'Of that thing',
  IVORY: 'Elephant tusk',
  KEEP: 'Hold on to',
  KITE: 'String flyer',
  KNOB: 'Door handle',
  KOALA: 'Aussie tree bear',
  LAB: 'Science room',
  LAG: 'Fall behind',
  LATEST: 'Most recent',
  LAW: 'Legal rule',
  LAY: 'Put down',
  LEEK: 'Onion relative',
  LEEWAY: 'Wiggle room',
  LEFT: 'Went away',
  LEMONADE: 'Summer drink',
  LENDER: 'Loan giver',
  LICENSE: 'Driver\'s permit',
  LIE: 'Fib',
  LION: 'Pride member',
  LIT: 'Switched on',
  LLAMA: 'Andean pack animal',
  LOST: 'Mislaid',
  LOT: 'A great deal',
  LUG: 'Haul',
  LUNCH: 'Midday meal',
  MAD: 'Furious',
  MANIA: 'Craze',
  MARVELOUS: 'Superb',
  MEAN: 'Unkind',
  MEDICAL: 'Of doctors',
  MEET: 'Come together',
  MELT: 'Turn to liquid',
  MENU: 'Diner\'s list',
  MET: 'Came across',
  MIDDLE: 'Center',
  MILE: '1,760 yards',
  MOAT: 'Castle ditch',
  MOBILE: 'Able to move',
  MODEM: 'Internet box',
  MUD: 'Wet dirt',
  MUM: 'Silent; mother',
  MUST: 'Have to',
  MYSTICAL: 'Magical',
  NAB: 'Catch',
  NATIONAL: 'Not local',
  NEURON: 'Nerve cell',
  NULL: 'Void',
  OAR: 'Rowing blade',
  OATH: 'Sworn promise',
  OBSERVER: 'Watcher',
  OCELOT: 'Spotted wild cat',
  ODE: 'Poem of praise',
  OGRE: 'Fairy-tale brute',
  OLD: 'Aged',
  ONE: 'Single',
  OPEN: 'Not shut',
  OPT: 'Choose',
  OPTIMIST: 'Glass-half-full type',
  ORE: 'Mined rock',
  OTTER: 'River swimmer',
  OUTER: 'Exterior',
  OVAL: 'Egg shape',
  OVER: 'Finished',
  OWL: 'Night bird',
  PADDED: 'Softly lined',
  PAL: 'Buddy',
  PEA: 'Pod seed',
  PEELER: 'Potato tool',
  PLOT: 'Story line',
  PRETZEL: 'Salty knot',
  PRIVATE: 'Not public',
  PUG: 'Flat-faced dog',
  PURCHASE: 'Buy',
  RABBLE: 'Unruly crowd',
  RADAR: 'Plane tracker',
  RAT: 'Sewer rodent',
  RAVE: 'Praise wildly',
  RAW: 'Uncooked',
  RAY: 'Beam of light',
  READ: 'Take in a book',
  RECOUP: 'Win back',
  RED: 'Ruby shade',
  REEF: 'Coral ridge',
  REGISTER: 'Sign up',
  RENT: 'Tenant\'s payment',
  RESET: 'Start over',
  RETRO: 'Old-style',
  RHAPSODY: 'Ecstatic piece',
  RISER: 'Step\'s upright',
  RITE: 'Ceremony',
  ROB: 'Steal from',
  RUE: 'Regret',
  RUT: 'Wheel groove',
  RYE: 'Bread grain',
  SAD: 'Unhappy',
  SAP: 'Tree juice',
  SCOOT: 'Hurry off',
  SCOWL: 'Angry look',
  SEA: 'Ocean',
  SEEM: 'Appear',
  SENATE: 'Upper house',
  SENSOR: 'Detector',
  SEW: 'Stitch',
  SHE: 'That woman',
  SIDEWALK: 'Pavement',
  SILO: 'Grain tower',
  SIR: 'Knight\'s title',
  SKY: 'Where clouds are',
  SLEW: 'A whole lot',
  SLUG: 'Garden pest',
  SLY: 'Cunning',
  SNEER: 'Scornful smile',
  SOCIETY: 'High ___',
  SOD: 'Turf',
  SODAS: 'Fizzy drinks',
  SOIL: 'Earth',
  SOLID: 'Not liquid',
  SPA: 'Wellness resort',
  SPRAWL: 'Spread out',
  SPY: 'Secret agent',
  STAMINA: 'Staying power',
  STAMP: 'Letter\'s sticker',
  STARTLE: 'Surprise',
  STATUE: 'Carved figure',
  STEER: 'Guide the wheel',
  SUB: 'Long sandwich',
  SWITCH: 'Light control',
  TAD: 'Tiny bit',
  TAMALE: 'Corn-husk dish',
  TEA: 'Leaf brew',
  TEAR: 'Rip',
  TEEN: '13 to 19',
  TENSION: 'Strain',
  TERN: 'Sea bird',
  TERSE: 'Curt',
  TEXT: 'Phone message',
  TIARA: 'Small crown',
  TILL: 'Cash drawer',
  TIPS: 'Waiter\'s extras',
  TONER: 'Printer powder',
  TRACER: 'Glowing bullet',
  TRY: 'Attempt',
  TUB: 'Bath',
  TUG: 'Pull hard',
  TUMOR: 'Growth',
  TURN: 'Rotate',
  TYPE: 'Kind; use a keyboard',
  UFO: 'Flying saucer',
  UMBRA: 'Full shadow',
  UPROOT: 'Pull out fully',
  URN: 'Ashes vessel',
  USE: 'Employ',
  UTOPIA: 'Perfect world',
  VEGAN: 'No animal products',
  VET: 'Animal doctor',
  VIED: 'Competed',
  VIOLIN: 'Fiddle',
  VOTER: 'Ballot caster',
  WASH: 'Clean with water',
  WED: 'Marry',
  WHAT: 'Pardon?',
  WHEN: 'At what time?',
  WHET: 'Sharpen',
  WIDE: 'Broad',
  WIT: 'Quick humor',
  WOVEN: 'Made on a loom',
  WRITE: 'Put on paper',
  WRONG: 'Not right',
  YAK: 'Shaggy ox',
  YAM: 'Sweet potato kin',
  YAPS: 'Barks shrilly',
  YARN: 'Knitting thread',
  YEAR: '365 days',
  YEN: 'Tokyo money',
  YIN: 'Yang\'s partner',
  YOU: 'Not me',
  ZANY: 'Wacky',
  ZEAL: 'Fervor',
};

type Baked = [answer: string, row: number, col: number, dir: Dir];

interface BakedPuzzle {
  id: string;
  title: string;
  entries: Baked[];
}

export const PUZZLES: Record<Difficulty, BakedPuzzle[]> = {
  easy: [
    {
      id: 'easy-1',
      title: 'Ballot box',
      // ··↓↓↓↓ / ·┼MUST / →VOTER / →EBONY / →TIPS· / ·→LION / ·→EAR·
      entries: [
        ['MOBILE', 1, 2, 'down'],
        ['MUST', 1, 2, 'right'],
        ['UTOPIA', 1, 3, 'down'],
        ['SENSOR', 1, 4, 'down'],
        ['TRY', 1, 5, 'down'],
        ['VET', 2, 1, 'down'],
        ['VOTER', 2, 1, 'right'],
        ['EBONY', 3, 1, 'right'],
        ['TIPS', 4, 1, 'right'],
        ['LION', 5, 2, 'right'],
        ['EAR', 6, 2, 'right']
      ]
    },
    {
      id: 'easy-2',
      title: 'Print shop',
      // ·↓↓↓·· / →DIG↓· / →OVER↓ / →TONER / ·→RITE / ·→YARN / ··→LOT
      entries: [
        ['DOT', 1, 1, 'down'],
        ['DIG', 1, 1, 'right'],
        ['IVORY', 1, 2, 'down'],
        ['GENIAL', 1, 3, 'down'],
        ['OVER', 2, 1, 'right'],
        ['RETRO', 2, 4, 'down'],
        ['TONER', 3, 1, 'right'],
        ['RENT', 3, 5, 'down'],
        ['RITE', 4, 2, 'right'],
        ['YARN', 5, 2, 'right'],
        ['LOT', 6, 3, 'right']
      ]
    },
    {
      id: 'easy-3',
      title: 'Kite day',
      // ··↓↓·· / ·┼KITE / →GOO↓↓ / →RADAR / →ALIKE / →MANIA / ··→END
      entries: [
        ['KOALA', 1, 2, 'down'],
        ['KITE', 1, 2, 'right'],
        ['IODINE', 1, 3, 'down'],
        ['GRAM', 2, 1, 'down'],
        ['GOO', 2, 1, 'right'],
        ['RADAR', 3, 1, 'right'],
        ['AKIN', 3, 4, 'down'],
        ['READ', 3, 5, 'down'],
        ['ALIKE', 4, 1, 'right'],
        ['MANIA', 5, 1, 'right'],
        ['END', 6, 3, 'right']
      ]
    }
  ],
  medium: [
    {
      id: 'medium-1',
      title: 'Toolbox',
      // ·↓↓↓↓↓· / →STEER↓ / →HAMMER / →EMBODY / ·┼ART↓E / →CLAIM· / →RECOUP / ·Y→END·
      entries: [
        ['SHE', 1, 1, 'down'],
        ['STEER', 1, 1, 'right'],
        ['TAMALE', 1, 2, 'down'],
        ['EMBRACE', 1, 3, 'down'],
        ['EMOTION', 1, 4, 'down'],
        ['RED', 1, 5, 'down'],
        ['HAMMER', 2, 1, 'right'],
        ['RYE', 2, 6, 'down'],
        ['EMBODY', 3, 1, 'right'],
        ['ART', 4, 2, 'right'],
        ['CRY', 5, 1, 'down'],
        ['CLAIM', 5, 1, 'right'],
        ['MUD', 5, 5, 'down'],
        ['RECOUP', 6, 1, 'right'],
        ['END', 7, 3, 'right']
      ]
    },
    {
      id: 'medium-2',
      title: 'Backstage',
      // ··↓↓··· / →SHE↓↓· / ·→AMEND / →ABUSE↓ / ··I┼TUB / ·→TIARA / ·→ACTOR / ·→TEEN·
      entries: [
        ['SHE', 1, 1, 'right'],
        ['HABITAT', 1, 2, 'down'],
        ['EMU', 1, 3, 'down'],
        ['AMEND', 2, 2, 'right'],
        ['ESTATE', 2, 4, 'down'],
        ['NEURON', 2, 5, 'down'],
        ['ABUSE', 3, 1, 'right'],
        ['TUB', 4, 4, 'right'],
        ['BAR', 4, 6, 'down'],
        ['TIARA', 5, 2, 'right'],
        ['ICE', 5, 3, 'down'],
        ['ACTOR', 6, 2, 'right'],
        ['TEEN', 7, 2, 'right']
      ]
    },
    {
      id: 'medium-3',
      title: 'Campfire',
      // ··↓↓↓↓· / ·┼KEEP↓ / →COMBAT / →RABBLE / →ALE↓↓R / →CARBON / ·K→SIR· / ···→GEM
      entries: [
        ['KOALA', 1, 2, 'down'],
        ['KEEP', 1, 2, 'right'],
        ['EMBERS', 1, 3, 'down'],
        ['EBB', 1, 4, 'down'],
        ['PAL', 1, 5, 'down'],
        ['CRACK', 2, 1, 'down'],
        ['COMBAT', 2, 1, 'right'],
        ['TERN', 2, 6, 'down'],
        ['RABBLE', 3, 1, 'right'],
        ['ALE', 4, 1, 'right'],
        ['CARBON', 5, 1, 'right'],
        ['BIG', 5, 4, 'down'],
        ['ORE', 5, 5, 'down'],
        ['SIR', 6, 3, 'right'],
        ['GEM', 7, 4, 'right']
      ]
    }
  ],
  hard: [
    {
      id: 'hard-1',
      title: 'Night shift',
      // ·↓↓↓↓↓·· / →MODEM·· / →IVORY·· / →LATEST· / →ELECT↓↓ / ···→TILL / ·↓↓↓┼CUE / →COURAGE / →AWFUL·K / →PLOT···
      entries: [
        ['MILE', 1, 1, 'down'],
        ['MODEM', 1, 1, 'right'],
        ['OVAL', 1, 2, 'down'],
        ['DOTE', 1, 3, 'down'],
        ['ERECT', 1, 4, 'down'],
        ['MYSTICAL', 1, 5, 'down'],
        ['IVORY', 2, 1, 'right'],
        ['LATEST', 3, 1, 'right'],
        ['ELECT', 4, 1, 'right'],
        ['TILL', 5, 4, 'right'],
        ['LUG', 5, 6, 'down'],
        ['LEEK', 5, 7, 'down'],
        ['CUE', 6, 5, 'right'],
        ['CAP', 7, 1, 'down'],
        ['COURAGE', 7, 1, 'right'],
        ['OWL', 7, 2, 'down'],
        ['UFO', 7, 3, 'down'],
        ['RUT', 7, 4, 'down'],
        ['AWFUL', 8, 1, 'right'],
        ['PLOT', 9, 1, 'right']
      ]
    },
    {
      id: 'hard-2',
      title: 'Workshop',
      // ·↓↓↓↓↓·· / →HOBBY↓· / →UPROOT· / →STATUE· / →HINT↓X· / ·↓M┼OATH / →GIZMO↓↓ / →USE→ROB / →STARTLE / ·H·L→ADD
      entries: [
        ['HUSH', 1, 1, 'down'],
        ['HOBBY', 1, 1, 'right'],
        ['OPTIMIST', 1, 2, 'down'],
        ['BRAN', 1, 3, 'down'],
        ['BOTTOM', 1, 4, 'down'],
        ['YOU', 1, 5, 'down'],
        ['UPROOT', 2, 1, 'right'],
        ['TEXT', 2, 6, 'down'],
        ['STATUE', 3, 1, 'right'],
        ['HINT', 4, 1, 'right'],
        ['OATH', 5, 4, 'right'],
        ['AORTA', 5, 5, 'down'],
        ['GUSH', 6, 1, 'down'],
        ['GIZMO', 6, 1, 'right'],
        ['ZEAL', 6, 3, 'down'],
        ['USE', 7, 1, 'right'],
        ['ROB', 7, 5, 'right'],
        ['OLD', 7, 6, 'down'],
        ['BED', 7, 7, 'down'],
        ['STARTLE', 8, 1, 'right'],
        ['ADD', 9, 5, 'right']
      ]
    },
    {
      id: 'hard-3',
      title: 'Corner shop',
      // ··↓↓↓··· / →LICENSE / ·→MUM↓↓· / ·┼BRINE↓ / →CULTURE / →HEY┼LAG / ·O↓┼ALSO / →KNOB·E· / →EARL··· / ·→BEE···
      entries: [
        ['LICENSE', 1, 1, 'right'],
        ['IMBUE', 1, 2, 'down'],
        ['CURLY', 1, 3, 'down'],
        ['EMIT', 1, 4, 'down'],
        ['MUM', 2, 2, 'right'],
        ['BRINE', 3, 2, 'right'],
        ['NULL', 3, 5, 'down'],
        ['ERASE', 3, 6, 'down'],
        ['CHOKE', 4, 1, 'down'],
        ['CULTURE', 4, 1, 'right'],
        ['EGO', 4, 7, 'down'],
        ['HEY', 5, 1, 'right'],
        ['LAG', 5, 5, 'right'],
        ['ABLE', 6, 4, 'down'],
        ['ALSO', 6, 4, 'right'],
        ['KNOB', 7, 1, 'right'],
        ['NAB', 7, 2, 'down'],
        ['ORE', 7, 3, 'down'],
        ['EARL', 8, 1, 'right'],
        ['BEE', 9, 2, 'right']
      ]
    }
  ],
  pro: [
    {
      id: 'pro-1',
      title: 'Lemonade stand',
      // ··↓↓↓···· / →MELT↓··· / ·┼SLUG↓↓· / →STAMINA↓ / →LEMONADE / →YEAR┼TUG / ··M↓┼SILO / ·↓→SCOOT· / →VIOLIN↓· / ·E→DELAY· / →TEAR→LAB / ··→SKY·K·
      entries: [
        ['MELT', 1, 1, 'right'],
        ['ESTEEM', 1, 2, 'down'],
        ['LLAMA', 1, 3, 'down'],
        ['TUMOR', 1, 4, 'down'],
        ['SLUG', 2, 2, 'right'],
        ['GIN', 2, 5, 'down'],
        ['SLY', 3, 1, 'down'],
        ['STAMINA', 3, 1, 'right'],
        ['NATIONAL', 3, 6, 'down'],
        ['ADULT', 3, 7, 'down'],
        ['LEMONADE', 4, 1, 'right'],
        ['EGO', 4, 8, 'down'],
        ['YEAR', 5, 1, 'right'],
        ['TUG', 5, 6, 'right'],
        ['SOIL', 6, 5, 'down'],
        ['SILO', 6, 5, 'right'],
        ['SODAS', 7, 3, 'down'],
        ['SCOOT', 7, 3, 'right'],
        ['CLERK', 7, 4, 'down'],
        ['VET', 8, 1, 'down'],
        ['VIOLIN', 8, 1, 'right'],
        ['DELAY', 9, 3, 'right'],
        ['YAK', 9, 7, 'down'],
        ['TEAR', 10, 1, 'right'],
        ['LAB', 10, 6, 'right'],
        ['SKY', 11, 3, 'right']
      ]
    },
    {
      id: 'pro-2',
      title: 'Switchboard',
      // ·↓↓↓··↓↓↓ / →SLEW→DAM / →WIT→EASE / →ITCH┼SPA / ·T↓H→WHEN / →CLEAR↓C· / →HID┼OPT· / ··E┼ONE↓· / ·↓┼EAGER↓ / →BEAR→LAW / →ART·→EVE / →GAS·→RED
      entries: [
        ['SWITCH', 1, 1, 'down'],
        ['SLEW', 1, 1, 'right'],
        ['LIT', 1, 2, 'down'],
        ['ETCHED', 1, 3, 'down'],
        ['DASH', 1, 6, 'down'],
        ['DAM', 1, 6, 'right'],
        ['ASPECT', 1, 7, 'down'],
        ['MEAN', 1, 8, 'down'],
        ['WIT', 2, 1, 'right'],
        ['EASE', 2, 5, 'right'],
        ['ITCH', 3, 1, 'right'],
        ['SPA', 3, 6, 'right'],
        ['WRONG', 4, 5, 'down'],
        ['WHEN', 4, 5, 'right'],
        ['CLEAR', 5, 1, 'right'],
        ['LIE', 5, 2, 'down'],
        ['HID', 6, 1, 'right'],
        ['OPT', 6, 5, 'right'],
        ['PEELER', 6, 6, 'down'],
        ['OAR', 7, 4, 'down'],
        ['ONE', 7, 4, 'right'],
        ['EATS', 8, 3, 'down'],
        ['EAGER', 8, 3, 'right'],
        ['RAVE', 8, 7, 'down'],
        ['BAG', 9, 1, 'down'],
        ['BEAR', 9, 1, 'right'],
        ['ERA', 9, 2, 'down'],
        ['LAW', 9, 6, 'right'],
        ['WED', 9, 8, 'down'],
        ['ART', 10, 1, 'right'],
        ['EVE', 10, 6, 'right'],
        ['GAS', 11, 1, 'right'],
        ['RED', 11, 6, 'right']
      ]
    },
    {
      id: 'pro-3',
      title: 'City hall',
      // ·↓↓↓↓↓↓↓· / →SIDEWALK / →PRIVATE· / →REGISTER / ·A↓┼CHEW· / →WHET┼MAD / →LAW┼SPY· / ·→RESET·· / →ARSON↓·· / ··O→LAY·· / ·→WRITE·· / ···→DENT·
      entries: [
        ['SPRAWL', 1, 1, 'down'],
        ['SIDEWALK', 1, 1, 'right'],
        ['IRE', 1, 2, 'down'],
        ['DIG', 1, 3, 'down'],
        ['EVICT', 1, 4, 'down'],
        ['WASH', 1, 5, 'down'],
        ['ATTEMPT', 1, 6, 'down'],
        ['LEEWAY', 1, 7, 'down'],
        ['PRIVATE', 2, 1, 'right'],
        ['REGISTER', 3, 1, 'right'],
        ['CHEW', 4, 4, 'right'],
        ['WHET', 5, 1, 'right'],
        ['HARROW', 5, 2, 'down'],
        ['EWES', 5, 3, 'down'],
        ['MAD', 5, 6, 'right'],
        ['LAW', 6, 1, 'right'],
        ['SENATE', 6, 5, 'down'],
        ['SPY', 6, 5, 'right'],
        ['RESET', 7, 2, 'right'],
        ['SOLID', 7, 4, 'down'],
        ['ARSON', 8, 1, 'right'],
        ['LAY', 9, 4, 'right'],
        ['YEN', 9, 6, 'down'],
        ['WRITE', 10, 2, 'right'],
        ['DENT', 11, 4, 'right']
      ]
    }
  ],
  extreme: [
    {
      id: 'extreme-1',
      title: 'Dragon\'s hoard',
      // ·↓·↓↓↓↓··· / →MARVELOUS / ·I→HERE··· / →DRAGON↓·· / ·D→PADDED· / ·L┼SNEER↓· / →EGO↓→RAY↓ / ·→ODE↓→SAP / ·→TYPE┼EMU / ·↓↓┼ICY↓↓G / →PURCHASE· / →ERA→OPEN· / →ANT·→SAD·
      entries: [
        ['MIDDLE', 1, 1, 'down'],
        ['MARVELOUS', 1, 1, 'right'],
        ['RHAPSODY', 1, 3, 'down'],
        ['VEGAN', 1, 4, 'down'],
        ['ERODE', 1, 5, 'down'],
        ['LENDER', 1, 6, 'down'],
        ['HERE', 2, 3, 'right'],
        ['DRAGON', 3, 1, 'right'],
        ['PADDED', 4, 3, 'right'],
        ['ERASE', 4, 7, 'down'],
        ['SNEER', 5, 3, 'right'],
        ['EGO', 6, 1, 'right'],
        ['GOT', 6, 2, 'down'],
        ['RAY', 6, 6, 'right'],
        ['YAM', 6, 8, 'down'],
        ['ODE', 7, 2, 'right'],
        ['EPIC', 7, 4, 'down'],
        ['SAP', 7, 7, 'right'],
        ['PUG', 7, 9, 'down'],
        ['TYPE', 8, 2, 'right'],
        ['ECHO', 8, 5, 'down'],
        ['EMU', 8, 7, 'right'],
        ['ICY', 9, 4, 'right'],
        ['YAPS', 9, 6, 'down'],
        ['PEA', 10, 1, 'down'],
        ['PURCHASE', 10, 1, 'right'],
        ['URN', 10, 2, 'down'],
        ['RAT', 10, 3, 'down'],
        ['SEA', 10, 7, 'down'],
        ['END', 10, 8, 'down'],
        ['ERA', 11, 1, 'right'],
        ['OPEN', 11, 5, 'right'],
        ['ANT', 12, 1, 'right'],
        ['SAD', 12, 6, 'right']
      ]
    },
    {
      id: 'extreme-2',
      title: 'Old society',
      // ·↓↓↓↓·↓↓·· / →SOCIETY↓· / →TURN→RAY· / →ATOP→AMID / →MENU↓C↓N· / →PRETZEL↓↓ / ·↓↓↓┼AROMA / →WOVEN→SOD / →ICILY→TAD / →DEED↓↓·T· / →ELDEST··· / ··O→RUE··· / ··T·→BARN·
      entries: [
        ['STAMP', 1, 1, 'down'],
        ['SOCIETY', 1, 1, 'right'],
        ['OUTER', 1, 2, 'down'],
        ['CRONE', 1, 3, 'down'],
        ['INPUT', 1, 4, 'down'],
        ['TRACER', 1, 6, 'down'],
        ['YAM', 1, 7, 'down'],
        ['TURN', 2, 1, 'right'],
        ['RAY', 2, 6, 'right'],
        ['YIN', 2, 8, 'down'],
        ['ATOP', 3, 1, 'right'],
        ['AMID', 3, 6, 'right'],
        ['MENU', 4, 1, 'right'],
        ['PRETZEL', 5, 1, 'right'],
        ['ZANY', 5, 5, 'down'],
        ['LOST', 5, 7, 'down'],
        ['AROMA', 6, 5, 'right'],
        ['MOAT', 6, 8, 'down'],
        ['ADD', 6, 9, 'down'],
        ['WIDE', 7, 1, 'down'],
        ['WOVEN', 7, 1, 'right'],
        ['OCELOT', 7, 2, 'down'],
        ['VIED', 7, 3, 'down'],
        ['ELDER', 7, 4, 'down'],
        ['SOD', 7, 7, 'right'],
        ['ICILY', 8, 1, 'right'],
        ['TAD', 8, 7, 'right'],
        ['DEED', 9, 1, 'right'],
        ['ELDEST', 10, 1, 'right'],
        ['SUB', 10, 5, 'down'],
        ['TEA', 10, 6, 'down'],
        ['RUE', 11, 4, 'right'],
        ['BARN', 12, 5, 'right']
      ]
    },
    {
      id: 'extreme-3',
      title: 'Clinic',
      // ·↓↓↓·↓↓↓↓· / →MET→SEEM· / →EXERCISE· / →DIN→OTTER / →ITS→WHAT· / ·C→INLET·· / ·A↓O↓┼RED· / →LUNCH↓↓·· / ·↓M┼HEAT↓· / →OBSERVER↓ / →GREW→AREA / →RAW→RISER / ·E···→LEFT
      entries: [
        ['MEDICAL', 1, 1, 'down'],
        ['MET', 1, 1, 'right'],
        ['EXIT', 1, 2, 'down'],
        ['TENSION', 1, 3, 'down'],
        ['SCOWL', 1, 5, 'down'],
        ['SEEM', 1, 5, 'right'],
        ['EITHER', 1, 6, 'down'],
        ['ESTATE', 1, 7, 'down'],
        ['MEET', 1, 8, 'down'],
        ['EXERCISE', 2, 1, 'right'],
        ['DIN', 3, 1, 'right'],
        ['OTTER', 3, 5, 'right'],
        ['ITS', 4, 1, 'right'],
        ['WHAT', 4, 5, 'right'],
        ['INLET', 5, 3, 'right'],
        ['RED', 6, 6, 'right'],
        ['LUNCH', 7, 1, 'right'],
        ['UMBRA', 7, 2, 'down'],
        ['CHEW', 7, 4, 'down'],
        ['HER', 7, 5, 'down'],
        ['HEAT', 8, 4, 'right'],
        ['AVAIL', 8, 6, 'down'],
        ['TERSE', 8, 7, 'down'],
        ['OGRE', 9, 1, 'down'],
        ['OBSERVER', 9, 1, 'right'],
        ['SEW', 9, 3, 'down'],
        ['REEF', 9, 8, 'down'],
        ['GREW', 10, 1, 'right'],
        ['AREA', 10, 6, 'right'],
        ['ART', 10, 9, 'down'],
        ['RAW', 11, 1, 'right'],
        ['RISER', 11, 5, 'right'],
        ['LEFT', 12, 6, 'right']
      ]
    }
  ]
};

/** attach the clues: a baked puzzle is a grid, the clue bank is the text */
export function toDef(p: BakedPuzzle): ArrowPuzzleDef {
  const entries: ArrowEntry[] = p.entries.map(([answer, row, col, dir]) => ({
    answer,
    row,
    col,
    dir,
    clue: CLUES[answer] ?? answer
  }));
  return { id: p.id, title: p.title, entries };
}

export function allPuzzles(): ArrowPuzzleDef[] {
  return (Object.keys(PUZZLES) as Difficulty[]).flatMap((d) => PUZZLES[d].map(toDef));
}

export function pickPuzzle(difficulty: Difficulty): ArrowPuzzleDef {
  const list = PUZZLES[difficulty];
  return toDef(list[Math.floor(Math.random() * list.length)]);
}
