import type { GameDefinition } from '../../platform/types';
import { gameIcons } from '../../platform/design/gameIcons';
import { SokobanGame } from './SokobanGame';
import { sokobanTutorial } from './tutorial';

export const sokobanDefinition: GameDefinition = {
  id: 'sokoban',
  category: 'spatial',
  name: 'Sokoban',
  tagline: 'Push every crate onto a target.',
  icon: gameIcons['sokoban'],
  component: SokobanGame,
  tutorial: sokobanTutorial,
  scoringNote:
    'Every level is generated by reverse construction, so it is always solvable — no dead ends you cannot undo out of. Score = 400 × difficulty (1–5) + an efficiency bonus up to 300 × difficulty scaled by par ÷ your pushes (matching par earns the full bonus), − 40 per hint and − 20 per restart. Boards grow 6×6 → 10×10 with 2 → 5 crates and more interior walls each tier.',
  assistFeatures: [
    {
      id: 'undo',
      name: 'Undo',
      description: 'Adds an Undo tool that steps back one move. Counts as help when used.',
      defaultOn: true
    },
    {
      id: 'deadlockWarn',
      name: 'Deadlock warning',
      description: 'Highlights a crate you have pushed into an unrecoverable corner. Counts as help.',
      defaultOn: true
    },
    {
      id: 'hint',
      name: 'Hint',
      description: 'Shows the next move of an optimal solution as a ghost arrow. Counts as help when used.',
      defaultOn: false
    }
  ]
};
